### ISSUE TITLE
Periscope stream dl no longer working with youtube-dl

### ISSUE THREAD

**Issue by Yoshidk** [rg3/youtube-dl#12625]
Periscope have changed something on their site, and now all streams are running from "www.pscp.tv" instaed of the previous www.periscope.tv, and now youtube-dl can no longer download periscopes.
This is the output:
```
D:\folder\Peri\bin>youtube-dl.exe -v https://www.pscp.tv/w/1lDGLRyowebxm
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.pscp.tv/w/1lDGLRyowebxm']
[debug] Encodings: locale cp1252, fs mbcs, out cp850, pref cp1252
[debug] youtube-dl version 2017.04.02
[debug] Python version 3.4.4 - Windows-10-10.0.14393
[debug] exe versions: ffmpeg N-85091-g23ae3cc
[debug] Proxy map: {}
[generic] 1lDGLRyowebxm: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 1lDGLRyowebxm: Downloading webpage
[generic] 1lDGLRyowebxm: Extracting information
[generic] card: Requesting header
WARNING: Falling back on generic information extractor.
[generic] card: Downloading webpage
[generic] card: Extracting information
ERROR: Unsupported URL: https://www.pscp.tv/w/1lDGLRyowebxm/card
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpol0xsjvy\build\youtube_dl\YoutubeDL.py", line 761, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpol0xsjvy\build\youtube_dl\extractor\common.py", line 428, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpol0xsjvy\build\youtube_dl\extractor\generic.py", line 2667, in _real_extract
youtube_dl.utils.UnsupportedError: Unsupported URL: https://www.pscp.tv/w/1lDGLRyowebxm/card

D:\folder\Peri\bin>
```

**Comment by dstftw** [comment]
This is already fixed.

**Comment by Yoshidk** [comment]
Should I do something different then, because it still does not work for me

**Comment by dstftw** [comment]
Wait for next release.
