### ISSUE TITLE
[youtube] Cannot identify player 'https://www.youtube.com/yts/jsbin/player-vflppxuSE/en_US/base.js'

### ISSUE THREAD

**Issue by amoschu** [rg3/youtube-dl#12885]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.04.26*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.04.26**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
$ youtube-dl -f "bestaudio[ext!=webm]/best[ext!=webm]" --verbose 'https://www.youtube.com/watch?v=0VF0BlXP-0Y'
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-f', u'bestaudio[ext!=webm]/best[ext!=webm]', u'--verbose', u'https://www.youtube.com/watch?v=0VF0BlXP-0Y']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.04.26
[debug] Python version 2.7.12 - CYGWIN_NT-6.1-2.6.1-0.305-5-3-x86_64-64bit
[debug] exe versions: ffmpeg N-82225-gb4e9252
[debug] Proxy map: {}
[youtube] 0VF0BlXP-0Y: Downloading webpage
[youtube] 0VF0BlXP-0Y: Downloading video info webpage
[youtube] 0VF0BlXP-0Y: Extracting video information
WARNING: unable to extract html5 player; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[youtube] {43} signature length 40.40, html5 player None
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/youtube_dl/extractor/youtube.py", line 1081, in _decrypt_signature
    video_id, player_url, s
  File "/usr/lib/python2.7/site-packages/youtube_dl/extractor/youtube.py", line 969, in _extract_signature_function
    raise ExtractorError('Cannot identify player %r' % player_url)
ExtractorError: Cannot identify player u'https://www.youtube.com/yts/jsbin/player-vflppxuSE/en_US/base.js'; please report this issue on https://yt-dl.org/bug . Make sure you are using thelatest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by ExtractorError(u"Cannot identify player u'https://www.youtube.com/yts/jsbin/player-vflppxuSE/en_US/base.js'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to callyoutube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/youtube_dl/extractor/youtube.py", line 1081, in _decrypt_signature
    video_id, player_url, s
  File "/usr/lib/python2.7/site-packages/youtube_dl/extractor/youtube.py", line 969, in _extract_signature_function
    raise ExtractorError('Cannot identify player %r' % player_url)
ExtractorError: Cannot identify player u'https://www.youtube.com/yts/jsbin/player-vflppxuSE/en_US/base.js'; please report this issue on https://yt-dl.org/bug . Make sure you are using thelatest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 760, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python2.7/site-packages/youtube_dl/extractor/common.py", line 429, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python2.7/site-packages/youtube_dl/extractor/youtube.py", line 1642, in _real_extract
    encrypted_sig, video_id, player_url, age_gate)
  File "/usr/lib/python2.7/site-packages/youtube_dl/extractor/youtube.py", line 1091, in _decrypt_signature
    'Signature extraction failed: ' + tb, cause=e)
ExtractorError: Signature extraction failed: Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/youtube_dl/extractor/youtube.py", line 1081, in _decrypt_signature
    video_id, player_url, s
  File "/usr/lib/python2.7/site-packages/youtube_dl/extractor/youtube.py", line 969, in _extract_signature_function
    raise ExtractorError('Cannot identify player %r' % player_url)
ExtractorError: Cannot identify player u'https://www.youtube.com/yts/jsbin/player-vflppxuSE/en_US/base.js'; please report this issue on https://yt-dl.org/bug . Make sure you are using thelatest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by ExtractorError(u"Cannot identify player u'https://www.youtube.com/yts/jsbin/player-vflppxuSE/en_US/base.js'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to callyoutube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by cjsanjay** [comment]
Facing similar issue
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.04.26
[debug] Python version 3.5.2 - Linux-4.4.0-72-generic-x86_64-with-Ubuntu-16.04-xenial
[debug] exe versions: ffmpeg 2.8.11-0ubuntu0.16.04.1, ffprobe 2.8.11-0ubuntu0.16.04.1, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] I6LnxOHZ14I: Downloading webpage
[youtube] I6LnxOHZ14I: Downloading video info webpage
[youtube] I6LnxOHZ14I: Extracting video information
unable to extract html5 player; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[youtube] {22} signature length 40.40, html5 player None
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "/home/sanjay/.local/lib/python3.5/site-packages/youtube_dl/extractor/youtube.py", line 1081, in _decrypt_signature
    video_id, player_url, s
  File "/home/sanjay/.local/lib/python3.5/site-packages/youtube_dl/extractor/youtube.py", line 969, in _extract_signature_function
    raise ExtractorError('Cannot identify player %r' % player_url)
youtube_dl.utils.ExtractorError: Cannot identify player 'https://www.youtube.com/yts/jsbin/player-vflppxuSE/en_US/base.js'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by ExtractorError("Cannot identify player 'https://www.youtube.com/yts/jsbin/player-vflppxuSE/en_US/base.js'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/home/sanjay/.local/lib/python3.5/site-packages/youtube_dl/extractor/youtube.py", line 1081, in _decrypt_signature
    video_id, player_url, s
  File "/home/sanjay/.local/lib/python3.5/site-packages/youtube_dl/extractor/youtube.py", line 969, in _extract_signature_function
    raise ExtractorError('Cannot identify player %r' % player_url)
youtube_dl.utils.ExtractorError: Cannot identify player 'https://www.youtube.com/yts/jsbin/player-vflppxuSE/en_US/base.js'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/home/sanjay/.local/lib/python3.5/site-packages/youtube_dl/extractor/youtube.py", line 1081, in _decrypt_signature
    video_id, player_url, s
  File "/home/sanjay/.local/lib/python3.5/site-packages/youtube_dl/extractor/youtube.py", line 969, in _extract_signature_function
    raise ExtractorError('Cannot identify player %r' % player_url)
youtube_dl.utils.ExtractorError: Cannot identify player 'https://www.youtube.com/yts/jsbin/player-vflppxuSE/en_US/base.js'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sanjay/.local/lib/python3.5/site-packages/youtube_dl/YoutubeDL.py", line 760, in extract_info
    ie_result = ie.extract(url)
  File "/home/sanjay/.local/lib/python3.5/site-packages/youtube_dl/extractor/common.py", line 429, in extract
    ie_result = self._real_extract(url)
  File "/home/sanjay/.local/lib/python3.5/site-packages/youtube_dl/extractor/youtube.py", line 1642, in _real_extract
    encrypted_sig, video_id, player_url, age_gate)
  File "/home/sanjay/.local/lib/python3.5/site-packages/youtube_dl/extractor/youtube.py", line 1091, in _decrypt_signature
    'Signature extraction failed: ' + tb, cause=e)
youtube_dl.utils.ExtractorError: Signature extraction failed: Traceback (most recent call last):
  File "/home/sanjay/.local/lib/python3.5/site-packages/youtube_dl/extractor/youtube.py", line 1081, in _decrypt_signature
    video_id, player_url, s
  File "/home/sanjay/.local/lib/python3.5/site-packages/youtube_dl/extractor/youtube.py", line 969, in _extract_signature_function
    raise ExtractorError('Cannot identify player %r' % player_url)
youtube_dl.utils.ExtractorError: Cannot identify player 'https://www.youtube.com/yts/jsbin/player-vflppxuSE/en_US/base.js'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by ExtractorError("Cannot identify player 'https://www.youtube.com/yts/jsbin/player-vflppxuSE/en_US/base.js'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by Mochlate** [comment]
It is apparent that youtube must have done some update that has messed with the format.  Give the devs a few hours to fix it.

**Comment by eminem136915514** [comment]
i met this problems ,and updated the new released version(4.26),it still doesn't work

**Comment by Mochlate** [comment]
@eminem136915514 this problem did no exists until today, 4/27 how would it be fixed in the 4/26 build?

**Comment by amoschu** [comment]
This may have fix it? (I added 'lang_REGION' to the player url regex)

```
$ diff /usr/lib/python2.7/site-packages/youtube_dl/extractor/youtube.py ~/youtube.py
966c966
<             r'.*?-(?P<id>[a-zA-Z0-9_-]+)(?:/watch_as3|/html5player(?:-new)?|/base)?\.(?P<ext>[a-z]+)$',
---
>             r'.*?-(?P<id>[a-zA-Z0-9_-]+)(?:/[a-z]{2}_[A-Z]{2})?(?:/watch_as3|/html5player(?:-new)?|/base)?\.(?P<ext>[a-z]+)$',
```

**Comment by protella** [comment]
That seems to have fixed it for me, amoschu. Thx

**Comment by Wasdsensei** [comment]
Any ideas on how one would achieve this in the Windows version? (Or maybe I should just be patient and wait for an update.)

**Comment by jianwen03** [comment]
Er sorry noob here how to I use the fix? I'm using ubuntu 16.04
`$ diff /usr/lib/python2.7/site-packages/youtube_dl/extractor/youtube.py ~/youtube.py
diff: /usr/lib/python2.7/site-packages/youtube_dl/extractor/youtube.py: No such file or directory
diff: /home/jw/youtube.py: No such file or directory`

**Comment by protella** [comment]
@jianwen03 
Edit: /usr/lib/python2.7/site-packages/youtube_dl/extractor/youtube.py
Find the first line in the fix above (line 966)
Replace with the second line. (beginning with the "r")

**Comment by randomentity93** [comment]
This fix worked, Thanks @amoschu

**Comment by jianwen03** [comment]
I don't have anything named 'site-packages' in /usr/lib/python2.7

**Comment by rodzky** [comment]
I am using the latest Windows exe version and the problem still persist. Please help me.

**Comment by k-e-keith** [comment]
Currently on Windows 10, running the latest version of youtube-dl; have been encountering this issue throughout the day as well.
Updated the deps.bat and youtube-dl and haven't had any luck.
Error enclosed below in case it's helpful.

Could not extract information from https://www.youtube.com/watch?v=-hHpSlEz73k&index=36&list=PL21BAA7C6EDEB63A3

```
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "C:\Users\Francois\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\extractor\youtube.py", line 1081, in _decrypt_signature
    video_id, player_url, s
  File "C:\Users\Francois\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\extractor\youtube.py", line 969, in _extract_signature_function
    raise ExtractorError('Cannot identify player %r' % player_url)
youtube_dl.utils.ExtractorError: Cannot identify player 'https://www.youtube.com/yts/jsbin/player-vflppxuSE/en_US/base.js'
 (caused by ExtractorError("Cannot identify player 'https://www.youtube.com/yts/jsbin/player-vflppxuSE/en_US/base.js'",))
```

**Comment by rodzky** [comment]
I have the same issue for the past 5hours already, I'm using windows exe version 04.26.2017
Please help :(


C:\Users\Administrator>youtube-dl -v --extract-audio --audio-format mp3 -o C:/yo
utube-downloads/%(id)s.%(ext)s http://www.youtube.com/watch?v=RgKAFK5djSk
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '--extract-audio', '--audio-format', 'mp3', '-
o', 'C:/youtube-downloads/%(id)s.%(ext)s', 'http://www.youtube.com/watch?v=RgKAF
K5djSk']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2017.04.26
[debug] Python version 3.4.4 - Windows-2012ServerR2-6.3.9600
[debug] exe versions: ffmpeg N-85588-g6108805, ffprobe N-85588-g6108805
[debug] Proxy map: {}
[youtube] RgKAFK5djSk: Downloading webpage
[youtube] RgKAFK5djSk: Downloading video info webpage
[youtube] RgKAFK5djSk: Extracting video information
WARNING: unable to extract html5 player; please report this issue on https://yt-
dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to
 update. Be sure to call youtube-dl with the --verbose flag and include its comp
lete output.
[youtube] {22} signature length 40.40, html5 player None
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpi8nwgst1\bu
ild\youtube_dl\extractor\youtube.py", line 1081, in _decrypt_signature
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpi8nwgst1\bu
ild\youtube_dl\extractor\youtube.py", line 969, in _extract_signature_function
youtube_dl.utils.ExtractorError: Cannot identify player 'https://www.youtube.com
/yts/jsbin/player-vflppxuSE/en_US/base.js'; please report this issue on https://
yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U
 to update. Be sure to call youtube-dl with the --verbose flag and include its c
omplete output.
 (caused by ExtractorError("Cannot identify player 'https://www.youtube.com/yts/
jsbin/player-vflppxuSE/en_US/base.js'; please report this issue on https://yt-dl
.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to u
pdate. Be sure to call youtube-dl with the --verbose flag and include its comple
te output.",)); please report this issue on https://yt-dl.org/bug . Make sure yo
u are using the latest version; type  youtube-dl -U  to update. Be sure to call
youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpi8nwgst1\bu
ild\youtube_dl\extractor\youtube.py", line 1081, in _decrypt_signature
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpi8nwgst1\bu
ild\youtube_dl\extractor\youtube.py", line 969, in _extract_signature_function
youtube_dl.utils.ExtractorError: Cannot identify player 'https://www.youtube.com
/yts/jsbin/player-vflppxuSE/en_US/base.js'; please report this issue on https://
yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U
 to update. Be sure to call youtube-dl with the --verbose flag and include its c
omplete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpi8nwgst1\bu
ild\youtube_dl\extractor\youtube.py", line 1081, in _decrypt_signature
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpi8nwgst1\bu
ild\youtube_dl\extractor\youtube.py", line 969, in _extract_signature_function
youtube_dl.utils.ExtractorError: Cannot identify player 'https://www.youtube.com
/yts/jsbin/player-vflppxuSE/en_US/base.js'; please report this issue on https://
yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U
 to update. Be sure to call youtube-dl with the --verbose flag and include its c
omplete output.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpi8nwgst1\bu
ild\youtube_dl\YoutubeDL.py", line 760, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpi8nwgst1\bu
ild\youtube_dl\extractor\common.py", line 429, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpi8nwgst1\bu
ild\youtube_dl\extractor\youtube.py", line 1642, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpi8nwgst1\bu
ild\youtube_dl\extractor\youtube.py", line 1091, in _decrypt_signature
youtube_dl.utils.ExtractorError: Signature extraction failed: Traceback (most re
cent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpi8nwgst1\bu
ild\youtube_dl\extractor\youtube.py", line 1081, in _decrypt_signature
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpi8nwgst1\bu
ild\youtube_dl\extractor\youtube.py", line 969, in _extract_signature_function
youtube_dl.utils.ExtractorError: Cannot identify player 'https://www.youtube.com
/yts/jsbin/player-vflppxuSE/en_US/base.js'; please report this issue on https://
yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U
 to update. Be sure to call youtube-dl with the --verbose flag and include its c
omplete output.
 (caused by ExtractorError("Cannot identify player 'https://www.youtube.com/yts/
jsbin/player-vflppxuSE/en_US/base.js'; please report this issue on https://yt-dl
.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to u
pdate. Be sure to call youtube-dl with the --verbose flag and include its comple
te output.",)); please report this issue on https://yt-dl.org/bug . Make sure yo
u are using the latest version; type  youtube-dl -U  to update. Be sure to call
youtube-dl with the --verbose flag and include its complete output.

**Comment by irrgit** [comment]
@amoschu  Thanks dude, easy fast fix.

**Comment by vedavrat** [comment]
""" 
> I don't have anything named 'site-packages' in /usr/lib/python2.7... help pls?
 


   I have it here:
`/usr/local/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py`

Or try to find it:
`locate youtube.py`

**Comment by vedavrat** [comment]
(https://github.com/rg3/youtube-dl/issues/12885#issuecomment-297897519)

@amoschu 
Thank you! 
Your fix for '**youtube_dl/extractor/youtube.py**' file helped !

**Comment by skeith** [comment]
strange, that fix does not work on me

**Comment by Midaychi** [comment]
Can confirm that the fix put forward by amoschu works on windows 10

**Comment by k-e-keith** [comment]
Any way for someone to more clearly explain the process for @amoschu 's fix re: Windows 10? 
Total noob here unsure on how to apply it.

**Comment by rodzky** [comment]
Seems like the issue only appears when downloading VEVO videos.
I tried some local videos and the error is not showing.

**Comment by yan12125** [comment]
I've uploaded a fix based on @amoschu's change. Feel free to leave comments if the problem is still.

**Comment by yan12125** [comment]
Reopen until a new version is uploaded. I don't have the GPG signing key so I can't do a release.

**Comment by inhahe** [comment]
I got this error too on the following URL: https://www.youtube.com/watch?v=S95kGU9C7RM
amoschu's fix worked, but I had to start up VMWare and start my Ubuntu VM and download, configure and make install YASM and FFMPEG and pip install youtube-dl just to make it work because I normally use youtube-dl.exe on Windows. Oh and I had to "find / -name youtube.py" too because it was under /usr/local/lib/blah blah blah instead of /usr/lib/blah blah blah.

**Comment by Javinator9889** [comment]
The same error as the others
Lastest 5 hours

**Comment by Javinator9889** [comment]
And I checked is with VEVO videos almost always

**Comment by hoangdoanh** [comment]
Thanks @amoschu . I have fixed it ! It work fine now .

**Comment by swaraasolutions** [comment]
I have applied the regex from the commit 27 minutes ago and after adding that i am still getting error with videos
`[debug] System config: [u'--prefer-free-formats']
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-g', u'https://www.youtube.com/watch?v=uvxPMp-ZoEA', u'--verbose']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.04.26
[debug] Python version 2.7.5 - Linux-3.10.0-514.6.1.el7.x86_64-x86_64-with-centos-7.3.1611-Core
[debug] exe versions: ffmpeg 2.8.8, ffprobe 2.8.8
[debug] Proxy map: {}
WARNING: unable to extract html5 player; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version                                                                                                      ; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1081, in _decrypt_signature
    video_id, player_url, s
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 969, in _extract_signature_function
    raise ExtractorError('Cannot identify player %r' % player_url)
ExtractorError: Cannot identify player u'https://www.youtube.com/yts/jsbin/player-vflppxuSE/en_US/base.js'; please report this issue on                                                                                                       https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with th                                                                                                      e --verbose flag and include its complete output.
 (caused by ExtractorError(u"Cannot identify player u'https://www.youtube.com/yts/jsbin/player-vflppxuSE/en_US/base.js'; please report                                                                                                       this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtu                                                                                                      be-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you a                                                                                                      re using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complet                                                                                                      e output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1081, in _decrypt_signature
    video_id, player_url, s
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 969, in _extract_signature_function
    raise ExtractorError('Cannot identify player %r' % player_url)
ExtractorError: Cannot identify player u'https://www.youtube.com/yts/jsbin/player-vflppxuSE/en_US/base.js'; please report this issue on                                                                                                       https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with th                                                                                                      e --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 760, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 429, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1642, in _real_extract
    encrypted_sig, video_id, player_url, age_gate)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1091, in _decrypt_signature
    'Signature extraction failed: ' + tb, cause=e)
ExtractorError: Signature extraction failed: Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1081, in _decrypt_signature
    video_id, player_url, s
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 969, in _extract_signature_function
    raise ExtractorError('Cannot identify player %r' % player_url)
ExtractorError: Cannot identify player u'https://www.youtube.com/yts/jsbin/player-vflppxuSE/en_US/base.js'; please report this issue on                                                                                                       https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with th                                                                                                      e --verbose flag and include its complete output.
 (caused by ExtractorError(u"Cannot identify player u'https://www.youtube.com/yts/jsbin/player-vflppxuSE/en_US/base.js'; please report                                                                                                       this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtu                                                                                                      be-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you a                                                                                                      re using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complet                                                                                                      e output.
`
This happens to videos in India if that helps

**Comment by inhahe** [comment]
I'm getting the error with every video I try now (I'm listening to random Frosty the Snowman covers). I see some people saying it's only VEVO videos, and I'm not sure what a VEVO video is (a video uploaded by the user VEVO?), but I don't think these are VEVO videos because I don't see VEVO anywhere on the page.

Here's the latest one that I got the error with: https://www.youtube.com/watch?v=MrJWl6QSzNk

**Comment by mattjis** [comment]
@inhahe yeah it's all videos for me too

@yan12125 how can I get youtube-dl to update to the version you just added a commit to?

**Comment by yan12125** [comment]
> how can I get youtube-dl to update to the version you just added a commit to?

A possible way is:
1. Download https://github.com/rg3/youtube-dl/archive/master.zip and extract it
2. Open CMD.exe/shell and cd to youtube-dl-master
3. Install Python from https://www.python.org/ or package managers (apt-get, yum, Homebrew, etc.)
4. Run ```python ./youtube_dl/__main__.py (the URL)```

**Comment by erdoukki** [comment]
commit https://github.com/rg3/youtube-dl/commit/e31fed95b4b3026c34cec85c38c89b9b5c98b3d6
applyed locally this fix resolved the issue.

Thanks.

**Comment by navidR** [comment]
How much it would take to become available from pip3 ?

**Comment by yan12125** [comment]
> How much it would take to become available from pip3 ?

If you have ```git```, you can use ```pip install --upgrade git+https://github.com/rg3/youtube-dl``` to fetch the latest commit. Otherwise you'll need to wait until the release manager @dstftw has spare time.

**Comment by irukukagika** [comment]
The fix worked. For those who have nothing under /usr/lib/python2.7/site-packages/ check in
 /usr/lib/python2.7/dist-packages/  - Python 2.7
/usr/lib/python3.5/site-packages/   - Python 3.5

**Comment by inhahe** [comment]
@irukukagika Mine was in /usr/local/lib/python2.7/site-packages. Forgive my linux n00bness if this is somehow a dumb comment. =)

**Comment by SuchKnife** [comment]
I still dont get it what to do, can someone please give me the full steps what to do? I've tried to go into YouTube.py , then edit with nodepat++, went to line 966, replaced every player url or something for lang_REGION , then I tried the bot, but still nothing works.

**Comment by arno01** [comment]
@SuchKnife just use the latest youtube-dl from the git master branch:

```
virtualenv ~/.venv/youtube-dl
. ~/.venv/youtube-dl/bin/activate
pip install --upgrade https://github.com/rg3/youtube-dl/archive/master.zip
alias youtube-dl=$(type -p youtube-dl) | tee -a ~/.bash_aliases
deactivate
```

There you go! :-)

**Comment by SuchKnife** [comment]
@arno01 Sorry i'm not really that kind of person to know these type of stuff, like what u said. I still have no idea what to do. Sorry! =(

**Comment by DukeMcAwesome** [comment]
@SuchKnife - in the Youtube.py which you accessed, you need to replace the regex on line 966 with 
`r'.*?-(?P<id>[a-zA-Z0-9_-]+)(?:/[a-z]{2}_[A-Z]{2})?(?:/watch_as3|/html5player(?:-new)?|/base)?\.(?P<ext>[a-z]+)$'`

**Comment by SuchKnife** [comment]
@DukeMcAwesome Thank you, It's fixed. Thanks everyone who helped <3

**Comment by war1an** [comment]
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'-f', u'bestaudio', u'dSYu8FLVr_Y', u'--exec', u'/usr/local/bin/ffmpeg -i {}  -codec:a libmp3lame -qscale:a 0 /Users/ivan/Documents/dSYu8FLVr_Y.mp3 && rm {}']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.04.26
[debug] Python version 2.7.10 - Darwin-16.5.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 3.2.4, ffprobe 3.2.4
[debug] Proxy map: {}
[youtube] dSYu8FLVr_Y: Downloading webpage
[youtube] dSYu8FLVr_Y: Downloading video info webpage
[youtube] dSYu8FLVr_Y: Extracting video information
WARNING: unable to extract html5 player; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[youtube] {22} signature length 40.40, html5 player None
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1081, in _decrypt_signature
    video_id, player_url, s
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 969, in _extract_signature_function
    raise ExtractorError('Cannot identify player %r' % player_url)
ExtractorError: Cannot identify player u'https://www.youtube.com/yts/jsbin/player-vflppxuSE/en_US/base.js'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by ExtractorError(u"Cannot identify player u'https://www.youtube.com/yts/jsbin/player-vflppxuSE/en_US/base.js'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1081, in _decrypt_signature
    video_id, player_url, s
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 969, in _extract_signature_function
    raise ExtractorError('Cannot identify player %r' % player_url)
ExtractorError: Cannot identify player u'https://www.youtube.com/yts/jsbin/player-vflppxuSE/en_US/base.js'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 760, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 429, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1642, in _real_extract
    encrypted_sig, video_id, player_url, age_gate)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1091, in _decrypt_signature
    'Signature extraction failed: ' + tb, cause=e)
ExtractorError: Signature extraction failed: Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 1081, in _decrypt_signature
    video_id, player_url, s
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 969, in _extract_signature_function
    raise ExtractorError('Cannot identify player %r' % player_url)
ExtractorError: Cannot identify player u'https://www.youtube.com/yts/jsbin/player-vflppxuSE/en_US/base.js'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by ExtractorError(u"Cannot identify player u'https://www.youtube.com/yts/jsbin/player-vflppxuSE/en_US/base.js'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by thereald3bug** [comment]
Problem still occurs as of right now under Windows 10.
Updated to latest EXE.  It is 7am EST.
URL for my video is: https://www.youtube.com/watch?v=QWLBtMz5OuY

Output is as follows:
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', '-f', '137+bestaudio', 'https://www.youtube.com/watch?v=QWLBtMz5OuY']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2017.04.26
[debug] Python version 3.4.4 - Windows-10-10.0.15063
[debug] exe versions: ffmpeg N-85469-gf1d80bc
[debug] Proxy map: {}
[youtube] QWLBtMz5OuY: Downloading webpage
[youtube] QWLBtMz5OuY: Downloading video info webpage
[youtube] QWLBtMz5OuY: Extracting video information
WARNING: unable to extract html5 player; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[youtube] {22} signature length 40.40, html5 player None
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpi8nwgst1\build\youtube_dl\extractor\youtube.py", line 1081, in _decrypt_signature
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpi8nwgst1\build\youtube_dl\extractor\youtube.py", line 969, in _extract_signature_function
youtube_dl.utils.ExtractorError: Cannot identify player 'https://www.youtube.com/yts/jsbin/player-vflppxuSE/en_US/base.js'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by ExtractorError("Cannot identify player 'https://www.youtube.com/yts/jsbin/player-vflppxuSE/en_US/base.js'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpi8nwgst1\build\youtube_dl\extractor\youtube.py", line 1081, in _decrypt_signature
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpi8nwgst1\build\youtube_dl\extractor\youtube.py", line 969, in _extract_signature_function
youtube_dl.utils.ExtractorError: Cannot identify player 'https://www.youtube.com/yts/jsbin/player-vflppxuSE/en_US/base.js'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpi8nwgst1\build\youtube_dl\extractor\youtube.py", line 1081, in _decrypt_signature
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpi8nwgst1\build\youtube_dl\extractor\youtube.py", line 969, in _extract_signature_function
youtube_dl.utils.ExtractorError: Cannot identify player 'https://www.youtube.com/yts/jsbin/player-vflppxuSE/en_US/base.js'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpi8nwgst1\build\youtube_dl\YoutubeDL.py", line 760, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpi8nwgst1\build\youtube_dl\extractor\common.py", line 429, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpi8nwgst1\build\youtube_dl\extractor\youtube.py", line 1642, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpi8nwgst1\build\youtube_dl\extractor\youtube.py", line 1091, in _decrypt_signature
youtube_dl.utils.ExtractorError: Signature extraction failed: Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpi8nwgst1\build\youtube_dl\extractor\youtube.py", line 1081, in _decrypt_signature
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpi8nwgst1\build\youtube_dl\extractor\youtube.py", line 969, in _extract_signature_function
youtube_dl.utils.ExtractorError: Cannot identify player 'https://www.youtube.com/yts/jsbin/player-vflppxuSE/en_US/base.js'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by ExtractorError("Cannot identify player 'https://www.youtube.com/yts/jsbin/player-vflppxuSE/en_US/base.js'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
