### ISSUE TITLE
WARNING: unable to obtain file audio codec with ffprobe

### ISSUE THREAD

**Issue by felixhelix** [rg3/youtube-dl#12979]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.05.01*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.05.01**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
 youtube-dl --extract-audio --audio-format best -v https://www.youtube.com/watch?v=i9-AtHiVHPo&list=PLp1hlZQFN4XzZHrG9tLWxPs6dJSvPmuTl
[debug] System config: []
[debug] User config: ['-x', '--no-mtime', '-o', '~/Music/%(title)s.%(ext)s']
[debug] Custom config: []
[debug] Command-line args: ['--extract-audio', '--audio-format', 'best', '-v', 'https://www.youtube.com/watch?v=i9-AtHiVHPo']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.05.01
[debug] Python version 3.5.2 - Linux-3.5.0-61-generic-x86_64-with-debian-wheezy-sid
[debug] exe versions: avconv 0.8.17-4, avprobe 0.8.17-4, ffmpeg 0.8.17-4, ffprobe 0.8.17-4
[debug] Proxy map: {}
[youtube] i9-AtHiVHPo: Downloading webpage
[youtube] i9-AtHiVHPo: Downloading video info webpage
[youtube] i9-AtHiVHPo: Extracting video information
[youtube] {43} signature length 40.40, html5 player vflppxuSE
[youtube] {18} signature length 40.40, html5 player vflppxuSE
[youtube] {36} signature length 40.40, html5 player vflppxuSE
[youtube] {17} signature length 40.40, html5 player vflppxuSE
[youtube] {134} signature length 40.40, html5 player vflppxuSE
[youtube] {243} signature length 40.40, html5 player vflppxuSE
[youtube] {133} signature length 40.40, html5 player vflppxuSE
[youtube] {242} signature length 40.40, html5 player vflppxuSE
[youtube] {160} signature length 40.40, html5 player vflppxuSE
[youtube] {278} signature length 40.40, html5 player vflppxuSE
[youtube] {140} signature length 40.40, html5 player vflppxuSE
[youtube] {171} signature length 40.40, html5 player vflppxuSE
[youtube] {249} signature length 40.40, html5 player vflppxuSE
[youtube] {250} signature length 40.40, html5 player vflppxuSE
[youtube] {251} signature length 40.40, html5 player vflppxuSE
[debug] Invoking downloader on 'https://r6---sn-oxujvavbox-jbol.googlevideo.com/videoplayback?requiressl=yes&initcwndbps=1475000&gir=yes&mime=audio%2Fwebm&key=yt6&mm=31&mn=sn-oxujvavbox-jbol&id=o-AA9yK2f6EUYEVmAdO2-Ux1FD4NlKqd7iI-dV_rO0qIEJ&keepalive=yes&clen=2865566&ip=87.79.41.237&mt=1493841506&mv=m&sparams=clen%2Cdur%2Cei%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Crequiressl%2Csource%2Cupn%2Cexpire&ms=au&pl=21&ei=ozYKWbmRC4ekWfn_mPgB&itag=251&source=youtube&upn=2omFoRaIoXU&ipbits=0&dur=164.361&expire=1493863171&lmt=1449597680032446&signature=5769190B5B901FF2C93B2861E36BC7D6646AAF99.E3695D2B1CC1785F63D46968F6BF42823936022E&ratebypass=yes'
[download] /home/felix/Music/Rocco Granata - Marina 2009.webm has already been downloaded
[download] 100% of 2.73MiB
[debug] avconv command line: avprobe -show_streams 'file:/home/felix/Music/Rocco Granata - Marina 2009.webm'
ERROR: WARNING: unable to obtain file audio codec with ffprobe
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1942, in post_process
    files_to_delete, info = pp.run(info)
  File "/usr/local/bin/youtube-dl/youtube_dl/postprocessor/ffmpeg.py", line 241, in run
    raise PostProcessingError('WARNING: unable to obtain file audio codec with ffprobe')
youtube_dl.utils.PostProcessingError: WARNING: unable to obtain file audio codec with ffprobe

```

### Description of your *issue*, suggested solution and other information
The downloaded file cannot be converted.
I also checked that ffprobe version:
 ffprobe -version
avprobe version 0.8.17-4:0.8.17-0ubuntu0.12.04.2, Copyright (c) 2007-2014 the Libav developers
  built on Apr  1 2016 14:24:20 with gcc 4.6.3
avprobe 0.8.17-4:0.8.17-0ubuntu0.12.04.2
libavutil    51. 22. 3 / 51. 22. 3
libavcodec   53. 35. 0 / 53. 35. 0
libavformat  53. 21. 1 / 53. 21. 1
libavdevice  53.  2. 0 / 53.  2. 0
libavfilter   2. 15. 0 /  2. 15. 0
libswscale    2.  1. 0 /  2.  1. 0
libpostproc  52.  0. 0 / 52.  0. 0

And also:

ffprobe -show_streams 'file:/home/felix/Music/Rocco Granata - Marina 2009.webm'
avprobe version 0.8.17-4:0.8.17-0ubuntu0.12.04.2, Copyright (c) 2007-2014 the Libav developers
  built on Apr  1 2016 14:24:20 with gcc 4.6.3
[matroska,webm @ 0x1f769a0] Unknown entry 0x56AA
[matroska,webm @ 0x1f769a0] Unknown entry 0x56BB
[matroska,webm @ 0x1f769a0] Unknown/unsupported CodecID A_OPUS.
[matroska,webm @ 0x1f769a0] Unknown entry 0x75A2
[matroska,webm @ 0x1f769a0] decoding for stream 0 failed
[matroska,webm @ 0x1f769a0] Estimating duration from bitrate, this may be inaccurate
file:/home/felix/Music/Rocco Granata - Marina 2009.webm: Operation not permitted

Seems like ffprobe isn't configured correctly, but I don't know how to fix it :-(

**Comment by yan12125** [comment]
0.8.17 is too old and broken in this case. The latest ffmpeg should fix it. You may want to specify ```--prefer-ffmpeg``` so that old avprobe won't be used.

**Comment by felixhelix** [comment]
Thanks for the quick reply :-)
However, using --prefer-ffmpeg didn't solve the issue. I will try to install an updated version of ffprobe and see if that will do.
