### ISSUE TITLE
[DAILYMOTION] An extractor error has occurred

### ISSUE THREAD

**Issue by Chtiadrien** [rg3/youtube-dl#17699]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.09.26*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.09.26**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
# local
➜  ~ youtube-dl -F https://www.dailymotion.com/video/x6udgbb --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-F', u'https://www.dailymotion.com/video/x6udgbb', u'--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.09.26
[debug] Python version 2.7.15 (CPython) - Darwin-17.7.0-x86_64-i386-64bit
[debug] exe versions: none
[debug] Proxy map: {}
[dailymotion] x6udgbb: Downloading webpage
ERROR: An extractor error has occurred. (caused by KeyError(u'metadata',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 507, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/dailymotion.py", line 175, in _real_extract
    metadata = player['metadata']
KeyError: u'metadata'
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 792, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 520, in extract
    raise ExtractorError('An extractor error has occurred.', cause=e)
ExtractorError: An extractor error has occurred. (caused by KeyError(u'metadata',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

```
# via ssh on a server
user@server:~$ youtube-dl -F https://www.dailymotion.com/video/x6udgbb --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-F', u'https://www.dailymotion.com/video/x6udgbb', u'--verbose']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.09.26
[debug] Python version 2.7.3 (CPython) - Linux-3.13-0.bpo.1-amd64-x86_64-with-debian-7.8
[debug] exe versions: ffmpeg 2.5.3, ffprobe 2.5.3
[debug] Proxy map: {}
[dailymotion] x6udgbb: Downloading webpage
ERROR: An extractor error has occurred. (caused by KeyError(u'metadata',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 507, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/dailymotion.py", line 175, in _real_extract
    metadata = player['metadata']
KeyError: u'metadata'
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 792, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 520, in extract
    raise ExtractorError('An extractor error has occurred.', cause=e)
ExtractorError: An extractor error has occurred. (caused by KeyError(u'metadata',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by mrfade** [comment]
[https://www.dailymotion.com/player/metadata/video/:videoId?integration=inline&GK_PV5_NEON=1](https://www.dailymotion.com/player/metadata/video/:videoId?integration=inline&GK_PV5_NEON=1) metadata url here, you can fix.

**Comment by ringofyre** [comment]
Can confirm from Australian ip. Same extractor error as OP.

**Comment by rbigm101** [comment]
Confirm; US ip.

**Comment by Mehmet4226** [comment]
[root@server htdocs]# youtube-dl https://www.dailymotion.com/video/xv0l0w --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'https://www.dailymotion.com/video/xv0l0w', u'--verbose']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.09.26
[debug] Python version 2.6.6 (CPython) - Linux-2.6.32-754.3.5.el6.x86_64-x86_64-with-centos-6.10-Final
[debug] exe versions: none
[debug] Proxy map: {}
[dailymotion] xv0l0w: Downloading webpage
ERROR: An extractor error has occurred. (caused by KeyError(u'metadata',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "./youtube-dl/youtube_dl/extractor/common.py", line 507, in extract
    ie_result = self._real_extract(url)
  File "./youtube-dl/youtube_dl/extractor/dailymotion.py", line 175, in _real_extract
    metadata = player['metadata']
KeyError: u'metadata'
Traceback (most recent call last):
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 792, in extract_info
    ie_result = ie.extract(url)
  File "./youtube-dl/youtube_dl/extractor/common.py", line 520, in extract
    raise ExtractorError('An extractor error has occurred.', cause=e)
ExtractorError: An extractor error has occurred. (caused by KeyError(u'metadata',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by Issue-Reporter2** [comment]
Hi Mehmet its already fixed https://github.com/rg3/youtube-dl/pull/17706/commits/cbc4c5757d7db2618df55a495819a305d2f70a1b

**Comment by pjbclarke** [comment]
I am not sure it is fixed. I just tried to download from dailymotion. It worked fine last week, but today I got

C:\Users\Peter\Downloads>youtube-dl https://www.dailymotion.com/video/x6u
[dailymotion] x6ui4y8: Downloading webpage
ERROR: An extractor error has occurred. (caused by KeyError('metadata',))
e report this issue on https://yt-dl.org/bug . Make sure you are using th
t version; type  youtube-dl -U  to update. Be sure to call youtube-dl wit
-verbose flag and include its complete output.

C:\Users\Peter\Downloads>youtube-dl -v https://www.dailymotion.com/video/

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.dailymotion.com/video/x6ui
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2018.09.26
[debug] Python version 3.4.4 (CPython) - Windows-7-6.1.7601-SP1
[debug] exe versions: none
[debug] Proxy map: {}
[dailymotion] x6ui4y8: Downloading webpage
ERROR: An extractor error has occurred. (caused by KeyError('metadata',))
e report this issue on https://yt-dl.org/bug . Make sure you are using th
t version; type  youtube-dl -U  to update. Be sure to call youtube-dl wit
-verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpcaq3
ild\youtube_dl\extractor\common.py", line 507, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpcaq3
ild\youtube_dl\extractor\dailymotion.py", line 175, in _real_extract
KeyError: 'metadata'
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpcaq3
ild\youtube_dl\extractor\common.py", line 507, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpcaq3
ild\youtube_dl\extractor\dailymotion.py", line 175, in _real_extract
KeyError: 'metadata'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpcaq3
ild\youtube_dl\YoutubeDL.py", line 792, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpcaq3
ild\youtube_dl\extractor\common.py", line 520, in extract
youtube_dl.utils.ExtractorError: An extractor error has occurred. (caused
Error('metadata',)); please report this issue on https://yt-dl.org/bug .
re you are using the latest version; type  youtube-dl -U  to update. Be s
call youtube-dl with the --verbose flag and include its complete output.

**Comment by bani6809** [comment]
version 2018.09.26.

confirmed not working from US IP.

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--ignore-config', '-i', '--proxy', '', '--verbose', 'https://www.dailymotion.com/video/x4jivt1']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2018.09.26
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17134
[debug] exe versions: ffmpeg N-90173-gfa0c9d69d3, ffprobe N-90173-gfa0c9d69d3
[debug] Proxy map: {}
[dailymotion] x4jivt1: Downloading webpage
ERROR: An extractor error has occurred. (caused by KeyError('metadata',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpcaq35cl9\build\youtube_dl\extractor\common.py", line 507, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpcaq35cl9\build\youtube_dl\extractor\dailymotion.py", line 175, in _real_extract
KeyError: 'metadata'
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpcaq35cl9\build\youtube_dl\extractor\common.py", line 507, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpcaq35cl9\build\youtube_dl\extractor\dailymotion.py", line 175, in _real_extract
KeyError: 'metadata'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpcaq35cl9\build\youtube_dl\YoutubeDL.py", line 792, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpcaq35cl9\build\youtube_dl\extractor\common.py", line 520, in extract
youtube_dl.utils.ExtractorError: An extractor error has occurred. (caused by KeyError('metadata',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by mrfade** [comment]
I fixed in my repo and I created a pull request but it hasn't merged yet. We hope it will be merged as soon as possible

**Comment by jesusgt** [comment]
Bug still present. UK

~/bin/youtube-dl --version
2018.09.26

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://www.dailymotion.com/video/x6uj3qj']
[debug] Encodings: locale ISO-8859-1, fs ISO-8859-1, out ISO-8859-1, pref ISO-8859-1
[debug] youtube-dl version 2018.09.26
[debug] Python version 2.7.14 (CPython) - Linux-4.4.0-109-generic-x86_64-with-debian-stretch-sid
[debug] exe versions: avconv 3.4.1-1, avprobe 3.4.1-1, ffmpeg 3.4.1-1, ffprobe 3.4.1-1
[debug] Proxy map: {}
[dailymotion] x6uj3qj: Downloading webpage
ERROR: An extractor error has occurred. (caused by KeyError(u'metadata',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/home/xuxo/bin/youtube-dl/youtube_dl/extractor/common.py", line 507, in extract
    ie_result = self._real_extract(url)
  File "/home/xuxo/bin/youtube-dl/youtube_dl/extractor/dailymotion.py", line 175, in _real_extract
    metadata = player['metadata']
KeyError: u'metadata'
Traceback (most recent call last):
  File "/home/xuxo/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 792, in extract_info
    ie_result = ie.extract(url)
  File "/home/xuxo/bin/youtube-dl/youtube_dl/extractor/common.py", line 520, in extract
    raise ExtractorError('An extractor error has occurred.', cause=e)
ExtractorError: An extractor error has occurred. (caused by KeyError(u'metadata',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
