### ISSUE TITLE
Can't download from vivo and redirect fails

### ISSUE THREAD

**Issue by alexanderluna** [rg3/youtube-dl#18157]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.11.07*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.11.07**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
 youtube-dl -v https://vivo.sx/390141c235
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'https://vivo.sx/390141c235']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.11.07
[debug] Python version 2.7.15 (CPython) - Darwin-18.2.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.0.2, ffprobe 4.0.2, phantomjs 2.1.1
[debug] Proxy map: {}
[Vivo] 390141c235: Downloading webpage
ERROR: Unable to extract stream; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 792, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 508, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/shared.py", line 22, in _real_extract
    video_url = self._extract_video_url(webpage, video_id, url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/shared.py", line 92, in _extract_video_url
    webpage, 'stream', group='url'),
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 983, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract stream; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

---

### Description of your *issue*, suggested solution and other information

2 updates ago I was able to use a link similar to this one `https://s.to/redirect/3511522` to download
videos. Youtube-dl would follow the redirect and download the video from VIVO. Now it doesn't follow the redirect and when I use the VIVO link directly it gives me this error.

**Comment by RokerHRO** [comment]
Duplicate to which open issue?

**Comment by DaDirnbocher** [comment]
[this one](https://github.com/rg3/youtube-dl/issues/18139)

**Comment by alexanderluna** [comment]
@DaDirnbocher The issue was closed without being resolved in the latest version `2018.11.07`

**Comment by albino1** [comment]
The issue was fixed *after* the 2018.11.07 release, so when the next release comes out it will be fixed in that one.

**Comment by DaDirnbocher** [comment]
@RokerHRO @alexanderluna the linked issue was reported with version 2018.11.07, of course it's not solved in this version.
@dstftw commited a [pull request](https://github.com/rg3/youtube-dl/commit/96a91b15513af2121be1dd93871cc3769c06da3e)  which is now verified and @dstftw [commented](https://github.com/rg3/youtube-dl/issues/18139#issuecomment-437700859) that the fix isnt released yet.

So the issue was reported with the current version, there is a (verified) fix (so solved ist corrent), but the fix isn't released yet. You have just to what for the next release and hope its coming soon.

**Comment by RokerHRO** [comment]
@DaDirnbocher : Okay. Thanks for clarification. :-)

**Comment by RokerHRO** [comment]
@DaDirnbocher : Works. Thank you! :-)
