### ISSUE TITLE
AtomicParsley error: bad mpeg4 file (ftyp atom missing or alignment error).

### ISSUE THREAD

**Issue by pricejn2** [rg3/youtube-dl#2768]
The ```--embed-thumbnail``` feature introduced in #2404 errors out when converting an mpeg4 file to any non-mpeg4 format, such as mp3 or aac.  Should we be using something like mutagen for these instead? 

```
youtube-dl -o "%(extractor)s-%(id)s.%(ext)s" --embed-thumbnail --restrict-filenames -f bestaudio --audio-format mp3 -x fNAAGMW3Nts -v
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-o', '%(extractor)s-%(id)s.%(ext)s', '--embed-thumbnail', '--restrict-filenames', '-f', 'bestaudio', '--audio-format', 'mp3', '-x', 'fNAAGMW3Nts', '-v']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2014.04.13
[debug] Python version 2.7.3 - Linux-3.2.0-4-amd64-x86_64-with-debian-7.4
[debug] Proxy map: {}
[youtube] Setting language
[youtube] fNAAGMW3Nts: Downloading webpage
[youtube] fNAAGMW3Nts: Downloading video info webpage
[youtube] fNAAGMW3Nts: Extracting video information
[download] Destination: youtube-fNAAGMW3Nts.m4a
[download] 100% of 3.62MiB in 00:01
[avconv] Destination: youtube-fNAAGMW3Nts.mp3
[debug] ffmpeg command line: avconv -y -i youtube-fNAAGMW3Nts.m4a -vn -acodec libmp3lame -q:a 5 youtube-fNAAGMW3Nts.mp3
[ffmpeg] Fixing audio file "youtube-fNAAGMW3Nts.mp3"
[debug] ffmpeg command line: avconv -y -i youtube-fNAAGMW3Nts.mp3 -vn -acodec copy youtube-fNAAGMW3Nts.temp.mp3
[atomicparsley] Adding thumbnail to "youtube-fNAAGMW3Nts.mp3"
[debug] AtomicParsley command line: AtomicParsley youtube-fNAAGMW3Nts.mp3 --artwork youtube-fNAAGMW3Nts.thumb.mp3 -o youtube-fNAAGMW3Nts.temp.mp3
ERROR: AtomicParsley error: bad mpeg4 file (ftyp atom missing or alignment error).
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/YoutubeDL.py", line 1070, in post_process
    keep_video_wish, new_info = pp.run(info)
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl/postprocessor/atomicparsley.py", line 50, in run
    raise AtomicParsleyPPError(msg)
AtomicParsleyPPError
```

**Comment by ptrakk** [comment]
same

**Comment by Nothing4You** [comment]
Still an issue

**Comment by pulpe** [comment]
Should be fixed by ddbed36. If you encounter another problems, please open a new issue.

**Comment by fohrums** [comment]
@pulpe 

Ran an update to now `youtube-dl_20150417`

using `atomicparsley-0.9.0` i'm still receiving that same error (bad mpeg4 file):

```
user@neptune /cygdrive/d/download
$ dl https://www.youtube.com/watch?v=2YQU-UABLbE
[youtube] 2YQU-UABLbE: Downloading webpage
[youtube] 2YQU-UABLbE: Extracting video information
[youtube] 2YQU-UABLbE: Downloading DASH manifest
[youtube] 2YQU-UABLbE: Downloading thumbnail ...
[youtube] 2YQU-UABLbE: Writing thumbnail to: CapitalSTEEZ Feat. Joey Bada$$ - Talking Shit-2YQU-UABLbE.jpg
[download] Destination: CapitalSTEEZ Feat. Joey Bada$$ - Talking Shit-2YQU-UABLbE.m4a
[download] 100% of 5.13MiB in 00:09
[ffmpeg] Correcting container in "CapitalSTEEZ Feat. Joey Bada$$ - Talking Shit-2YQU-UABLbE.m4a"
[ffmpeg] Destination: CapitalSTEEZ Feat. Joey Bada$$ - Talking Shit-2YQU-UABLbE.mp3
Deleting original file CapitalSTEEZ Feat. Joey Bada$$ - Talking Shit-2YQU-UABLbE.m4a (pass -k to keep)
[ffmpeg] Fixing audio file "CapitalSTEEZ Feat. Joey Bada$$ - Talking Shit-2YQU-UABLbE.mp3"
[atomicparsley] Adding thumbnail to "CapitalSTEEZ Feat. Joey Bada$$ - Talking Shit-2YQU-UABLbE.mp3"
ERROR: AtomicParsley error: bad mpeg4 file (ftyp atom missing or alignment error).
```

**Comment by pulpe** [comment]
@fohrums Wait for release or use version from git.

**Comment by XDjackieXD** [comment]
I cloned the latest git build and get this error (and it leaves a thumb.mp3 file without audio in addition to the mp3 file):
```
../youtube-dl/youtube-dl --audio-quality 0 -o "%(title)s.%(ext)s" -c -i -w --audio-format mp3 --embed-thumbnail --add-metadata https://soundcloud.com/sparxmusic/sparx-refraction-ft-adhesive
[soundcloud] sparxmusic/sparx-refraction-ft-adhesive: Resolving id
[soundcloud] sparxmusic/sparx-refraction-ft-adhesive: Downloading info JSON
[soundcloud] 90044980: Downloading track url
[soundcloud] 90044980: Checking fallback video format URL
[soundcloud] 90044980: Checking http_mp3_128_url video format URL
[download] Sparx - Refraction (Ft. Adhesive Wombat).mp3 has already been downloaded
[download] 100% of 3.72MiB
[ffmpeg] Adding metadata to 'Sparx - Refraction (Ft. Adhesive Wombat).mp3'
[ffmpeg] Adding thumbnail to "Sparx - Refraction (Ft. Adhesive Wombat).mp3"
ERROR: Sparx - Refraction (Ft. Adhesive Wombat).thumb.mp3: could not find codec parameters
```

**Comment by pulpe** [comment]
@XDjackieXD Please open a new issue with full output, use '--verbose' option. Thanks
