### ISSUE TITLE
Slow on Raspberry Pi

### ISSUE THREAD

**Issue by giampiero7** [rg3/youtube-dl#3029]
Hi,
I'm running youtube-dl on a raspberry pi (Raspbian GNU/Linux 7 (wheezy))...
youtube-dl seems to be slow on each operation. Even just calling "youtube-dl --version" returns after about 7 seconds...
Anyone with the same problem?

**Comment by gyppo** [comment]
This also occurs on Raspi with Arch Linux ARM. Version 2015.03.09 takes about 12s to run --version, and -g (what I'm mainly using it for) takes 22s.

**Comment by acpadhi** [comment]
Any updates on this yet ? It has been almost more than an year since the issue was raised, and no solution so far. I have checked Python doing other stuff pretty fast on the same Pi as it is expected.

So unlikely, there is any issue with python. May be there is something, that the new versions are trying to do which is causing this wait ~14 seconds issue.

**Comment by dstftw** [comment]
@acpadhi run `strace -o yt-dl-strace.log -t -fff youtube-dl --verbose` and post the `yt-dl-strace.log` file.

**Comment by acpadhi** [comment]
There were multiple ones created. Zipped them up into a single file. Please download the below link.
http://transworldsoft.net/pi/all_strace_logs.tar.gz

**Comment by acpadhi** [comment]
@dstftw  any update on this ? Did the logs work for you or need any other info ?
I am planning to use this in one of my projects, and the delay it has now makes it just unusable. Tried with quvi, but quvi fails with some videos which have signature requirements. Some videos requiring the signature param work in quvi and some do not. those that do not do play in youtube-dl.

**Comment by SharkWipf** [comment]
I ran into this issue as well and decided to dive into the code to check it out. 
I noticed that on every single execution of youtube-dl, regardless of what you're trying to do with it, it imports every single download module youtube-dl has, which in turn import their own dependencies.
By removing all imports I didn't need from [this file](https://github.com/rg3/youtube-dl/blob/fd3a1f/youtube_dl/extractor/__init__.py) and just leaving the 3 sites I need, I cut down the execution time from 8-9 seconds to 2 seconds.
Still a lot, even on the RasPi, but a whole lot lot less.

I haven't looked into the code much deeper, but it seems at least the bulk of the delay is caused by loading the ~900 downloading modules and their dependencies on every execution of youtube-dl.
Honestly I'm surprised it works as fast as it does on "proper" computers.
I'd suggest dynamically loading modules when necessary, rather than always loading everything you can load.
I haven't looked into where the remaining 2 seconds load time come from yet, but 2 seconds execution time works well enough for me for now.

**Comment by remitamine** [comment]
> but it seems at least the bulk of the delay is caused by loading the ~900 downloading modules and their dependencies on every execution of youtube-dl.
i will post some ideas that may be can help to solve this problem:
first method(lazy loading of extractors):
by sepate the detection if the extractor(YoutubeDL.py will handle this indirectly) is needed and the extraction logic.
- generate meta-data about extractors and determine what extractor is needed from this metadata.
for example saving the the extractor path and the regex and let YoutubeDl.py to load the metadata and decide when the extractor is needed(match the entred urls with the the _VALID_URL) what's not good about this is the duplication of information, the need for regeneration after every change in regex and it doesn't fit for every extrator(some extractors don't depend only on the _VALID_URL) but the good about it .
or
- separte the declaration of the extraction logic and the code to know if the extractor is needed or not(_VALID_URL and suitable) in different files.
or ...(some ideas by developers).

the second method is to prevent youtube-dl from exiting so it will load only once and make than let the user to interact with with opened process(i think this will be simpler to implement than the first two ideas and it doesn't involve a lot of changes).
i think it will be good for others also to share ideas may we can find a good solution.

**Comment by yan12125** [comment]
I believe this problem is already fixed with #8497. Feel free to paste your timing results if it's still slow with lazy extractors.

Unzipping files may help, too.

**Comment by Dingo64** [comment]
The problem is still on ARM Debian 8. It takes about 10 seconds to see version number.
I installed using:
```
curl -L https://yt-dl.org/downloads/latest/youtube-dl -o /usr/local/bin/youtube-dl
chmod a+rx /usr/local/bin/youtube-dl
```
The version number is the newest: 2018.01.07
Next time I installed using pip and it shows version number in a 2-3 seconds. But pip doesn't offer up-to-date version and the newest I got from pip is 2017.12.31.

**Comment by yan12125** [comment]
@Dingo64: You may want a custom build with lazy extractors enabled: https://github.com/rg3/youtube-dl/pull/8497#issuecomment-269499733

**Comment by Dingo64** [comment]
Thanks, I'll try
