### ISSUE TITLE
BiliBili extractor downloads only a part ot the video

### ISSUE THREAD

**Issue by Rudloff** [rg3/youtube-dl#3250]
When I try to download [this video](http://www.bilibili.com/video/av1018498/), it downloads only the first 6 minutes.

**Comment by wanglongqi** [comment]
Yes, it will only download the first part of the video. As is implemented in the code:

        lq_durl = lq_doc.find('./durl')
        formats = [{
            'format_id': 'lq',
            'quality': 1,
            'url': lq_durl.find('./url').text,
            'filesize': int_or_none(
                lq_durl.find('./size'), get_attr='text'),
        }]

`lq_durl.find('./url').text` uses `find` method, and thus only the first part of the video will be reported from extractor. I agree this extractor should be enhanced as most of the video on bilibili is splited into parts and meanwhile the playlist is not handled correctly as well.

**Comment by yan12125** [comment]
Thanks @Rudloff for the report and @wanglongqi for digging the problem. I've fixed bilibili extractor and in the next version of youtube-dl multipart videos can be downloaded correctly. @Rudloff The video you provide is not accessible for me, so I use http://www.bilibili.com/video/av1041170/ as the test case.

**Comment by playfulpachyderm** [comment]
This is still an issue for me on version `2018.04.16`, though it looks like the cause is slightly different.  It looks like it tries to re-download the same video part 6 times, and 5 of them it ignores saying "has already been downloaded".

```C:\Users\User>youtube-dl -v https://www.bilibili.com/video/av7850279
[debug] System config: []
[debug] User config: ['--no-mtime', '-o', 'C:/Users/User/Music/%(title)s.%(ext)s']
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.bilibili.com/video/av7850279']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2018.04.16
[debug] Python version 3.5.2 (CPython) - Windows-10-10.0.16299-SP0
[debug] exe versions: ffmpeg 3.3.2, ffprobe 3.3.2
[debug] Proxy map: {}
[BiliBili] 7850279: Downloading webpage
[BiliBili] 7850279: Downloading video info page
[download] Downloading playlist: 2017年维也纳新年音乐会 Neujahrskonzert 2017 mit Gustavo Dudamel
[BiliBili] playlist 2017年维也纳新年音乐会 Neujahrskonzert 2017 mit Gustavo Dudamel: Collected 6 video ids (downloading 6 of them)
[download] Downloading video 1 of 6
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'http://upos-hz-mirrorcos.acgvideo.com/upgcxcode/06/40/12894006/12894006-1-80.flv?um_deadline=1524433461&platform=pc&rate=387600&oi=1677375490&um_sign=ae1edf04ba6d55a3e3b8dfb42bf7c43e&gen=playurl&os=cos&trid=76fdbc75e615421b821e02661f95ab67'
[download] Destination: C:\Users\User\Music\2017年维也纳新年音乐会 Neujahrskonzert 2017 mit Gustavo Dudamel.flv
[download] 100% of 74.17MiB in 02:47
[download] Downloading video 2 of 6
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'http://upos-hz-mirrorcos.acgvideo.com/upgcxcode/06/40/12894006/12894006-2-80.flv?um_deadline=1524433461&platform=pc&rate=426700&oi=1677375490&um_sign=3f9a30abdb2b93422fc561b4495b205e&gen=playurl&os=cos&trid=76fdbc75e615421b821e02661f95ab67'
[download] C:\Users\User\Music\2017年维也纳新年音乐会 Neujahrskonzert 2017 mit Gustavo Dudamel.flv has already been downloaded
[download] 100% of 74.17MiB
[download] Downloading video 3 of 6
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'http://upos-hz-mirrorcos.acgvideo.com/upgcxcode/06/40/12894006/12894006-3-80.flv?um_deadline=1524433461&platform=pc&rate=387600&oi=1677375490&um_sign=3c2f9c27a7fcf449927e83194b148396&gen=playurl&os=cos&trid=76fdbc75e615421b821e02661f95ab67'
[download] C:\Users\User\Music\2017年维也纳新年音乐会 Neujahrskonzert 2017 mit Gustavo Dudamel.flv has already been downloaded
[download] 100% of 74.17MiB
[download] Downloading video 4 of 6
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'http://upos-hz-mirrorcos.acgvideo.com/upgcxcode/06/40/12894006/12894006-4-80.flv?um_deadline=1524433461&platform=pc&rate=418200&oi=1677375490&um_sign=510a4d800e364c02940715e2520c2118&gen=playurl&os=cos&trid=76fdbc75e615421b821e02661f95ab67'
[download] C:\Users\User\Music\2017年维也纳新年音乐会 Neujahrskonzert 2017 mit Gustavo Dudamel.flv has already been downloaded
[download] 100% of 74.17MiB
[download] Downloading video 5 of 6
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'http://upos-hz-mirrorcos.acgvideo.com/upgcxcode/06/40/12894006/12894006-5-80.flv?um_deadline=1524433461&platform=pc&rate=453900&oi=1677375490&um_sign=8e4a8f8758e15947b50e700b0cc6116d&gen=playurl&os=cos&trid=76fdbc75e615421b821e02661f95ab67'
[download] C:\Users\User\Music\2017年维也纳新年音乐会 Neujahrskonzert 2017 mit Gustavo Dudamel.flv has already been downloaded
[download] 100% of 74.17MiB
[download] Downloading video 6 of 6
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'http://upos-hz-mirrorcos.acgvideo.com/upgcxcode/06/40/12894006/12894006-6-80.flv?um_deadline=1524433461&platform=pc&rate=498100&oi=1677375490&um_sign=da79e4d37556cde86364e797934944dd&gen=playurl&os=cos&trid=76fdbc75e615421b821e02661f95ab67'
[download] C:\Users\User\Music\2017年维也纳新年音乐会 Neujahrskonzert 2017 mit Gustavo Dudamel.flv has already been downloaded
[download] 100% of 74.17MiB
[download] Finished downloading playlist: 2017年维也纳新年音乐会 Neujahrskonzert 2017 mit Gustavo Dudamel
```
