### ISSUE TITLE
Extractor error

### ISSUE THREAD

**Issue by yatara** [rg3/youtube-dl#7413]
youtube-dl is up-to-date (2015.11.02)

youtube-dl -t --extract-audio --audio-format mp3 "https://www.youtube.com/watch?v=CeSo4rwJoq8"
[youtube] CeSo4rwJoq8: Downloading webpage
[youtube] CeSo4rwJoq8: Downloading video info webpage
[youtube] CeSo4rwJoq8: Extracting video information
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 817, in _decrypt_signature
    video_id, player_url, s
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 709, in _extract_signature_function
    raise ExtractorError('Cannot identify player %r' % player_url)
ExtractorError: Cannot identify player u'https://s.ytimg.com/yts/jsbin/player-en_US-vfljDEtYP/base.js'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by ExtractorError(u"Cannot identify player u'https://s.ytimg.com/yts/jsbin/player-en_US-vfljDEtYP/base.js'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

YataCurious

**Comment by paulguy** [comment]
I get this error too:  here's more verobse output:
```
$ youtube-dl --verbose https://www.youtube.com/watch?v=N_GPxe91hWE
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'https://www.youtube.com/watch?v=N_GPxe91hWE']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.11.02
[debug] Python version 2.7.10 - Linux-4.0.5-gentoo-x86_64-Intel-R-_Core-TM-_i7-2600_CPU_@_3.40GHz-with-gentoo-2.2
[debug] exe versions: ffmpeg N-75911-gf05ff05, ffprobe N-75911-gf05ff05, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] N_GPxe91hWE: Downloading webpage
[youtube] N_GPxe91hWE: Downloading video info webpage
[youtube] N_GPxe91hWE: Extracting video information
WARNING: unable to extract html5 player; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[youtube] {43} signature length 40.44, html5 player None
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/youtube_dl/extractor/youtube.py", line 817, in _decrypt_signature
    video_id, player_url, s
  File "/usr/lib64/python2.7/site-packages/youtube_dl/extractor/youtube.py", line 709, in _extract_signature_function
    raise ExtractorError('Cannot identify player %r' % player_url)
ExtractorError: Cannot identify player u'https://s.ytimg.com/yts/jsbin/player-en_US-vfljDEtYP/base.js'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by ExtractorError(u"Cannot identify player u'https://s.ytimg.com/yts/jsbin/player-en_US-vfljDEtYP/base.js'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/youtube_dl/extractor/youtube.py", line 817, in _decrypt_signature
    video_id, player_url, s
  File "/usr/lib64/python2.7/site-packages/youtube_dl/extractor/youtube.py", line 709, in _extract_signature_function
    raise ExtractorError('Cannot identify player %r' % player_url)
ExtractorError: Cannot identify player u'https://s.ytimg.com/yts/jsbin/player-en_US-vfljDEtYP/base.js'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 661, in extract_info
    ie_result = ie.extract(url)
  File "/usr/lib64/python2.7/site-packages/youtube_dl/extractor/common.py", line 290, in extract
    return self._real_extract(url)
  File "/usr/lib64/python2.7/site-packages/youtube_dl/extractor/youtube.py", line 1345, in _real_extract
    encrypted_sig, video_id, player_url, age_gate)
  File "/usr/lib64/python2.7/site-packages/youtube_dl/extractor/youtube.py", line 827, in _decrypt_signature
    'Signature extraction failed: ' + tb, cause=e)
ExtractorError: Signature extraction failed: Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/youtube_dl/extractor/youtube.py", line 817, in _decrypt_signature
    video_id, player_url, s
  File "/usr/lib64/python2.7/site-packages/youtube_dl/extractor/youtube.py", line 709, in _extract_signature_function
    raise ExtractorError('Cannot identify player %r' % player_url)
ExtractorError: Cannot identify player u'https://s.ytimg.com/yts/jsbin/player-en_US-vfljDEtYP/base.js'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by ExtractorError(u"Cannot identify player u'https://s.ytimg.com/yts/jsbin/player-en_US-vfljDEtYP/base.js'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

This is youtube-dl version 2015.11.02 on Gentoo Linux using Python 2.7.10.

**Comment by Acumero** [comment]
I'm getting the same issue. It looks like the url isn't matching the regex on [extractor/youtube.py:706](https://github.com/rg3/youtube-dl/blob/master/youtube_dl/extractor/youtube.py#L706).

**Comment by hhhorb** [comment]
Stopped working for me a few hours ago too...

`youtube-dl --verbose https://www.youtube.com/watch?v=XjwZAa2EjKA
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--verbose', u'https://www.youtube.com/watch?v=XjwZAa2EjKA']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2015.11.02
[debug] Python version 2.7.9 - Linux-4.2.0-0.bpo.1-686-pae-i686-with-debian-8.2
[debug] exe versions: avconv 2.8-1, avprobe 2.8-1, ffmpeg 2.8-1, ffprobe 2.8-1
[debug] Proxy map: {}
[youtube] XjwZAa2EjKA: Downloading webpage
[youtube] XjwZAa2EjKA: Downloading video info webpage
[youtube] XjwZAa2EjKA: Extracting video information
WARNING: unable to extract html5 player;`

`ERROR: Signature extraction failed: Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 817, in _decrypt_signature
    video_id, player_url, s
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 709, in _extract_signature_function
    raise ExtractorError('Cannot identify player %r' % player_url)`

**Comment by yan12125** [comment]
This should be fixed since 50f84a9ae171233c08ada41e03f6555c5ed95236. It will work in the next version.

@phihag I guess it's an important fix and we should have a new version.

**Comment by edbergavera** [comment]
Hi Guys,

Would downgrading to previous version a work around?

**Comment by lol768** [comment]
The commit message suggests a "new base.js html5 player" has been introduced (I'm guessing by Google) so I wouldn't have thought so, @edbergavera.

**Comment by yan12125** [comment]
@edbergavera A new version (2015.11.10) is released and I think it's the only working version as of now.

**Comment by phihag** [comment]
Version 2015.11.10 includes the fix. See [our FAQ](https://yt-dl.org/update) on how to upgrade.

**Comment by hhhorb** [comment]
Confirmed fixed with 2015.11.10. That's amazing work, doodz, thanks!

**Comment by Sindreedelange** [comment]
I am still getting this error:

> [debug] Custom config: []                                                                                                                                              │(base) stian@medGPU-ML-1:~/Master_thesis_fork/st-gcn$
[debug] Command-line args: ['https://www.youtube.com/watch?v=EjYFRsiWlWI', '--verbose']                                                                                │
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8                                                                                                       │
[debug] youtube-dl version 2018.12.03                                                                                                                                  │
[debug] Python version 3.6.8 (CPython) - Linux-4.15.0-32-generic-x86_64-with-debian-stretch-sid                                                                        │
[debug] exe versions: ffmpeg 4.0.2, ffprobe 4.0.2                                                                                                                      │
[debug] Proxy map: {}                                                                                                                                                  │
[youtube] EjYFRsiWlWI: Downloading webpage                                                                                                                             │
[youtube] EjYFRsiWlWI: Downloading video info webpage                                                                                                                  │
WARNING: unable to extract html5 player; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update │
 on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.                                                                 │
[youtube] {22} signature length 41.42, html5 player None                                                                                                               │
[youtube] EjYFRsiWlWI: Downloading player https://www.youtube.com/yts/jsbin/player_ias-vflRtzyEV/en_US/base.js                                                         │
ERROR: Signature extraction failed: Traceback (most recent call last):                                                                                                 │
  File "/home/stian/anaconda3/lib/python3.6/site-packages/youtube_dl/extractor/youtube.py", line 1225, in _decrypt_signature                                           │
    video_id, player_url, s                                                                                                                                            │
  File "/home/stian/anaconda3/lib/python3.6/site-packages/youtube_dl/extractor/youtube.py", line 1133, in _extract_signature_function                                  │
    res = self._parse_sig_js(code)                                                                                                                                     │
  File "/home/stian/anaconda3/lib/python3.6/site-packages/youtube_dl/extractor/youtube.py", line 1200, in _parse_sig_js                                                │
    initial_function = jsi.extract_function(funcname)                                                                                                                  │
  File "/home/stian/anaconda3/lib/python3.6/site-packages/youtube_dl/jsinterp.py", line 245, in extract_function                                                       │
    raise ExtractorError('Could not find JS function %r' % funcname)                                                                                                   │
youtube_dl.utils.ExtractorError: Could not find JS function 'encodeURIComponent'; please report this issue on https://yt-dl.org/bug . Make sure you are using the lates│
t version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.                        │
 (caused by ExtractorError("Could not find JS function 'encodeURIComponent'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest ver│
sion; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issu│
e on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose│
 flag and include its complete output.                                                                                                                                 │
Traceback (most recent call last):                                                                                                                                     │
  File "/home/stian/anaconda3/lib/python3.6/site-packages/youtube_dl/extractor/youtube.py", line 1225, in _decrypt_signature                                           │
    video_id, player_url, s                                                                                                                                            │
  File "/home/stian/anaconda3/lib/python3.6/site-packages/youtube_dl/extractor/youtube.py", line 1133, in _extract_signature_function                                  │
    res = self._parse_sig_js(code)                                                                                                                                     │
  File "/home/stian/anaconda3/lib/python3.6/site-packages/youtube_dl/extractor/youtube.py", line 1200, in _parse_sig_js                                                │
    initial_function = jsi.extract_function(funcname)                                                                                                                  │
  File "/home/stian/anaconda3/lib/python3.6/site-packages/youtube_dl/jsinterp.py", line 245, in extract_function                                                       │
    raise ExtractorError('Could not find JS function %r' % funcname)                                                                                                   │
youtube_dl.utils.ExtractorError: Could not find JS function 'encodeURIComponent'; please report this issue on https://yt-dl.org/bug . Make sure you are using the lates│
t version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.                        │
Traceback (most recent call last):                                                                                                                                     │
  File "/home/stian/anaconda3/lib/python3.6/site-packages/youtube_dl/extractor/youtube.py", line 1225, in _decrypt_signature                                           │
    video_id, player_url, s                                                                                                                                            │
  File "/home/stian/anaconda3/lib/python3.6/site-packages/youtube_dl/extractor/youtube.py", line 1133, in _extract_signature_function                                  │
    res = self._parse_sig_js(code)                                                                                                                                     │
  File "/home/stian/anaconda3/lib/python3.6/site-packages/youtube_dl/extractor/youtube.py", line 1200, in _parse_sig_js                                                │
    initial_function = jsi.extract_function(funcname)                                                                                                                  │
  File "/home/stian/anaconda3/lib/python3.6/site-packages/youtube_dl/jsinterp.py", line 245, in extract_function                                                       │
    raise ExtractorError('Could not find JS function %r' % funcname)                                                                                                   │
youtube_dl.utils.ExtractorError: Could not find JS function 'encodeURIComponent'; please report this issue on https://yt-dl.org/bug . Make sure you are using the lates│
t version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.                        │
                                                                                                                                                                       │
During handling of the above exception, another exception occurred:                                                                                                    │
                                                                                                                                                                       │
Traceback (most recent call last):                                                                                                                                     │
  File "/home/stian/anaconda3/lib/python3.6/site-packages/youtube_dl/YoutubeDL.py", line 792, in extract_info                                                          │
    ie_result = ie.extract(url)                                                                                                                                        │
  File "/home/stian/anaconda3/lib/python3.6/site-packages/youtube_dl/extractor/common.py", line 508, in extract                                                        │
    ie_result = self._real_extract(url)                                                                                                                                │
  File "/home/stian/anaconda3/lib/python3.6/site-packages/youtube_dl/extractor/youtube.py", line 1837, in _real_extract                                                │
    encrypted_sig, video_id, player_url, age_gate)                                                                                                                     │
  File "/home/stian/anaconda3/lib/python3.6/site-packages/youtube_dl/extractor/youtube.py", line 1235, in _decrypt_signature                                           │
    'Signature extraction failed: ' + tb, cause=e)                                                                                                                     │
youtube_dl.utils.ExtractorError: Signature extraction failed: Traceback (most recent call last):                                                                       │
  File "/home/stian/anaconda3/lib/python3.6/site-packages/youtube_dl/extractor/youtube.py", line 1225, in _decrypt_signature                                           │
    video_id, player_url, s                                                                                                                                            │
  File "/home/stian/anaconda3/lib/python3.6/site-packages/youtube_dl/extractor/youtube.py", line 1133, in _extract_signature_function                                  │
    res = self._parse_sig_js(code)                                                                                                                                     │
  File "/home/stian/anaconda3/lib/python3.6/site-packages/youtube_dl/extractor/youtube.py", line 1200, in _parse_sig_js                                                │
    initial_function = jsi.extract_function(funcname)                                                                                                                  │
  File "/home/stian/anaconda3/lib/python3.6/site-packages/youtube_dl/jsinterp.py", line 245, in extract_function                                                       │
    raise ExtractorError('Could not find JS function %r' % funcname)                                                                                                   │
youtube_dl.utils.ExtractorError: Could not find JS function 'encodeURIComponent'; please report this issue on https://yt-dl.org/bug . Make sure you are using the lates│
t version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.                        │
 (caused by ExtractorError("Could not find JS function 'encodeURIComponent'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest ver│
sion; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issu│
e on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose├──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
 flag and include its complete output.
