### ISSUE TITLE
Youtube audio download failure

### ISSUE THREAD

**Issue by robertmx** [rg3/youtube-dl#8033]
Audio extraction fails for a certain Youtube video. Verbose stderr and stdout are attached.

[youtube-dl-stderr.txt](https://github.com/rg3/youtube-dl/files/73081/youtube-dl-stderr.txt)
[youtube-dl-stdout.txt](https://github.com/rg3/youtube-dl/files/73080/youtube-dl-stdout.txt)

**Comment by yan12125** [comment]
In your ```youtube-dl-stderr.txt```:

> [debug] youtube-dl version 2015.11.24

You are using an out-dated version. This problem is fixed recently. Please update your copy to the latest version (2015.12.23) via [update instructions](https://github.com/rg3/youtube-dl/#how-do-i-update-youtube-dl).

**Comment by robertmx** [comment]
Ah damn I updated to 2015.12.23 but the old version was still present at a higher priority in the PATH. Sorry for the unnecessary hassle.
