### ISSUE TITLE
Dailymotion not working

### ISSUE THREAD

**Issue by LadySerenaKitty** [rg3/youtube-dl#8216]
I tried downloading some stuffies off DailyMotion, and it didn't work out so well.

I discovered the URL passed to ffmpeg just needs a little modification!  The URL ends with "#cell=nyc" and when I manually run ffmpeg without the "#cell=nyc" part, it works.

Copypasta (with verbose)
[jlhawkwell@Caracal:~/Movies/mlp/s1] youtube-dl -v https://www.dailymotion.com/playlist/x44mcj_My-Little-Pony-Episodes_my-little-pony-friendship-is-magic-season-1/1
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'https://www.dailymotion.com/playlist/x44mcj_My-Little-Pony-Episodes_my-little-pony-friendship-is-magic-season-1/1']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.01.09
[debug] Python version 2.7.11 - Darwin-15.2.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 2.8.4, ffprobe 2.8.4
[debug] Proxy map: {}
[dailymotion:playlist] x44mcj_My-Little-Pony-Episodes_my-little-pony-friendship-is-magic-season-1: Downloading webpage
[download] Downloading playlist: My Little Pony Friendship is Magic Season 1
[dailymotion:playlist] x44mcj_My-Little-Pony-Episodes_my-little-pony-friendship-is-magic-season-1: Downloading page 1
[dailymotion:playlist] x44mcj_My-Little-Pony-Episodes_my-little-pony-friendship-is-magic-season-1: Downloading page 2
[dailymotion:playlist] playlist My Little Pony Friendship is Magic Season 1: Downloading 26 videos
[download] Downloading video 1 of 26
[dailymotion] x3asofu: Downloading webpage
[dailymotion] x3asofu: Downloading m3u8 information
[debug] Invoking downloader on u'http://proxy-14.nyc.dailymotion.com/sec(3f584a9db52e2d7f0f1367911ca48b19)/video/037/235/199532730_mp4_h264_aac_hd.m3u8#cell=nyc'
[download] Destination: My Little Pony Friendship is Magic Season 1 Episode 1 Friendship Is Magic Part 1_2-x3asofu.mp4
[debug] ffmpeg command line: ffmpeg -y -headers 'Accept-Language: en-us,en;q=0.5
Accept-Encoding: gzip, deflate
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:10.0) Gecko/20150101 Firefox/20.0 (Chrome)
Accept-Charset: ISO-8859-1,utf-8;q=0.7,*;q=0.7
Cookie: dmvk=5695a4e4865df; ts=216206; v1st=293F715C656D7FCB32A00DBCBB46DC7E
' -i 'http://proxy-14.nyc.dailymotion.com/sec(3f584a9db52e2d7f0f1367911ca48b19)/video/037/235/199532730_mp4_h264_aac_hd.m3u8#cell=nyc' -f mp4 -c copy -bsf:a aac_adtstoasc 'file:My Little Pony Friendship is Magic Season 1 Episode 1 Friendship Is Magic Part 1_2-x3asofu.mp4.part'
ffmpeg version 2.8.4 Copyright (c) 2000-2015 the FFmpeg developers
  built with Apple LLVM version 7.0.2 (clang-700.1.81)
  configuration: --prefix=/opt/local --enable-swscale --enable-avfilter --enable-avresample --enable-libmp3lame --enable-libvorbis --enable-libopus --enable-libtheora --enable-libschroedinger --enable-libopenjpeg --enable-libmodplug --enable-libvpx --enable-libsoxr --enable-libspeex --enable-libass --enable-libbluray --enable-lzma --enable-gnutls --enable-fontconfig --enable-libfreetype --enable-libfribidi --disable-indev=jack --disable-outdev=xv --mandir=/opt/local/share/man --enable-shared --enable-pthreads --cc=/usr/bin/clang --enable-vda --enable-videotoolbox --arch=x86_64 --enable-yasm --enable-gpl --enable-postproc --enable-libx264 --enable-libxvid
  libavutil      54. 31.100 / 54. 31.100
  libavcodec     56. 60.100 / 56. 60.100
  libavformat    56. 40.101 / 56. 40.101
  libavdevice    56.  4.100 / 56.  4.100
  libavfilter     5. 40.101 /  5. 40.101
  libavresample   2.  1.  0 /  2.  1.  0
  libswscale      3.  1.101 /  3.  1.101
  libswresample   1.  2.101 /  1.  2.101
  libpostproc    53.  3.100 / 53.  3.100
[http @ 0x7fc769530520] HTTP error 404 Not Found
http://proxy-14.nyc.dailymotion.com/sec(3f584a9db52e2d7f0f1367911ca48b19)/video/037/235/199532730_mp4_h264_aac_hd.m3u8#cell=nyc: Server returned 404 Not Found

ERROR: ffmpeg exited with code 1
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/opt/local/bin/youtube-dl/__main__.py", line 19, in <module>
    youtube_dl.main()
  File "/opt/local/bin/youtube-dl/youtube_dl/__init__.py", line 410, in main
    _real_main(argv)
  File "/opt/local/bin/youtube-dl/youtube_dl/__init__.py", line 400, in _real_main
    retcode = ydl.download(all_urls)
  File "/opt/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1677, in download
    url, force_generic_extractor=self.params.get('force_generic_extractor', False))
  File "/opt/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 676, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/opt/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 837, in process_ie_result
    extra_info=extra)
  File "/opt/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 729, in process_ie_result
    extra_info=extra_info)
  File "/opt/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 676, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/opt/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 722, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "/opt/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1347, in process_video_result
    self.process_info(new_info)
  File "/opt/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1609, in process_info
    success = dl(filename, info_dict)
  File "/opt/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 1551, in dl
    return fd.download(name, info)
  File "/opt/local/bin/youtube-dl/youtube_dl/downloader/common.py", line 342, in download
    return self.real_download(filename, info_dict)
  File "/opt/local/bin/youtube-dl/youtube_dl/downloader/hls.py", line 63, in real_download
    self.report_error('%s exited with code %d' % (ffpp.basename, retval))
  File "/opt/local/bin/youtube-dl/youtube_dl/downloader/common.py", line 155, in report_error
    self.ydl.report_error(*args, **kargs)
  File "/opt/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 540, in report_error
    self.trouble(error_message, tb)
  File "/opt/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 502, in trouble
    tb_data = traceback.format_list(traceback.extract_stack())

[jlhawkwell@Caracal:~/Movies/mlp/s1]

Copypasta of WORKING ffmpeg command:
ffmpeg -y -i 'http://proxy-14.nyc.dailymotion.com/sec(3f584a9db52e2d7f0f1367911ca48b19)/video/037/235/199532730_mp4_h264_aac_hd.m3u8' -f mp4 -c copy -bsf:a aac_adtstoasc 'file:My Little Pony Friendship is Magic Season 1 Episode 1 Friendship Is Magic Part 1_2-x3asofu.mp4.part'

**Comment by dstftw** [comment]
Duplicate of #8156.

**Comment by tyrone-mt** [comment]
Hi,

Are there any updates about this issue please?

**Comment by yan12125** [comment]
It's fixed in git master but not released yet. Please wait for the next version.

**Comment by LadySerenaKitty** [comment]
Part of the problem is I compiled from teh git sources and I still have this problem.  It's specifically due to the "#cell=nyc" part at the end of the URL.  Without that, things work just fine.
