### ISSUE TITLE
Hitbox streams cannot be played since version 2015-12-29

### ISSUE THREAD

**Issue by NimGangstaCat** [rg3/youtube-dl#8217]
As the title says, Hitbox streams (at least) cannot be played since version 2015-12-29.

The error is the following:
```
$ mpv http://www.hitbox.tv/musify
Playing: http://www.hitbox.tv/musify
[ffmpeg] HandShake: client signature does not match!
[ffmpeg] Closing connection: NetStream.Play.StreamNotFound
Failed to open rtmp://hitboxeu01livefs.fplive.net/hitboxeu01live-live/stream_musify.
```

The work around `mpv $(youtube-dl -g "http://www.hitbox.tv/musify")` produces the exact same output.

Here's the full output:
```
$ youtube-dl -v http://www.hitbox.tv/musify
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.hitbox.tv/musify']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.01.09
[debug] Python version 2.7.11 - Linux-4.3.3_2-x86_64-with-libc
[debug] exe versions: rtmpdump 2.4
[debug] Proxy map: {}
[hitbox:live] musify: Downloading JSON metadata
[hitbox:live] musify: Downloading metadata JSON
[debug] Invoking downloader on u'rtmp://hitboxeu01livefs.fplive.net/hitboxeu01live-live/stream_musify'
[download] Destination: Musify - 24_7 Music and Gaming Stream Friendly 2016-01-13 03_14-musify.mp4
[debug] rtmpdump command line: rtmpdump --verbose -r rtmp://hitboxeu01livefs.fplive.net/hitboxeu01live-live/stream_musify -o 'Musify - 24_7 Music and Gaming Stream Friendly 2016-01-13 03_14-musify.mp4.part' --swfVfy http://www.hitbox.tv/static/player/flowplayer/flowplayer.commercial-3.2.16.swf --pageUrl http://www.hitbox.tv/musify --live
[rtmpdump] RTMPDump v2.4
[rtmpdump] (c) 2010 Andrej Stepanchuk, Howard Chu, The Flvstreamer Team; license: GPL
[rtmpdump] DEBUG: Parsing...
[rtmpdump] DEBUG: Parsed protocol: 0
[rtmpdump] DEBUG: Parsed host    : hitboxeu01livefs.fplive.net
[rtmpdump] DEBUG: Parsed app     : hitboxeu01live-live
[rtmpdump] DEBUG: Protocol : RTMP
[rtmpdump] DEBUG: Hostname : hitboxeu01livefs.fplive.net
[rtmpdump] DEBUG: Port     : 1935
[rtmpdump] DEBUG: Playpath : stream_musify
[rtmpdump] DEBUG: tcUrl    : rtmp://hitboxeu01livefs.fplive.net:1935/hitboxeu01live-live
[rtmpdump] DEBUG: swfUrl   : http://www.hitbox.tv/static/player/flowplayer/flowplayer.commercial-3.2.16.swf
[rtmpdump] DEBUG: pageUrl  : http://www.hitbox.tv/musify
[rtmpdump] DEBUG: app      : hitboxeu01live-live
[rtmpdump] DEBUG: live     : yes
[rtmpdump] DEBUG: timeout  : 30 sec
[rtmpdump] DEBUG: SWFSHA256:
[rtmpdump] DEBUG: 75 20 ee cf 7b 4f 33 46 25 47 28 ab 53 ad 99 c4
[rtmpdump] DEBUG: bd 80 0e 34 c7 8c cf 47 55 31 70 a0 98 6b 88 a3
[rtmpdump] DEBUG: SWFSize  : 259809
[rtmpdump] DEBUG: Setting buffer time to: 36000000ms
[rtmpdump] Connecting ...
[rtmpdump] DEBUG: RTMP_Connect1, ... connected, handshaking
[rtmpdump] DEBUG: HandShake: Client type: 03
[rtmpdump] DEBUG: HandShake: Client digest offset: 12
[rtmpdump] DEBUG: HandShake: Initial client digest: 
[rtmpdump] DEBUG: c3 45 c5 56 e9 d3 d3 50 49 2b eb 39 25 ba 25 44
[rtmpdump] DEBUG: ec 05 be 8e cd 8f 75 26 c4 22 ca e6 1a 3f d7 de
[rtmpdump] DEBUG: HandShake: Type Answer   : 03
[rtmpdump] DEBUG: HandShake: Server Uptime : 1910653130
[rtmpdump] DEBUG: HandShake: FMS Version   : 4.5.3.1
[rtmpdump] DEBUG: HandShake: Calculated digest key from secure key and server digest: 
[rtmpdump] DEBUG: 5d 69 9c bf c2 5e b4 af 1e bc 9c 8e 84 66 b3 9c
[rtmpdump] DEBUG: c9 e0 24 06 3b aa 65 2b e0 60 dc 04 a4 6c ec f6
[rtmpdump] DEBUG: HandShake: Client signature calculated:
[rtmpdump] DEBUG: d2 ea e5 60 e8 31 10 a6 99 e9 06 35 e4 74 31 a0
[rtmpdump] DEBUG: b8 48 00 74 fc 09 bf d0 ac 40 05 01 c8 94 d7 35
[rtmpdump] DEBUG: HandShake: Server sent signature:
[rtmpdump] DEBUG: ef 4d d8 4a ff e4 84 81 d0 9a 30 79 8b 24 52 95
[rtmpdump] DEBUG: 49 b1 dc d8 56 3a d4 ff cf 8d fa 3f 75 4d 99 40
[rtmpdump] DEBUG: HandShake: Digest key: 
[rtmpdump] DEBUG: 03 da 1b 88 ce 76 84 19 a3 3e f6 ce a4 31 45 0c
[rtmpdump] DEBUG: d3 c3 85 e9 3c 74 30 22 f6 8f 6d 60 ae 38 a6 bc
[rtmpdump] DEBUG: HandShake: Signature calculated:
[rtmpdump] DEBUG: ef 4d d8 4a ff e4 84 81 d0 9a 30 79 8b 24 52 95
[rtmpdump] DEBUG: 49 b1 dc d8 56 3a d4 ff cf 8d fa 3f 75 4d 99 40
[rtmpdump] DEBUG: HandShake: Genuine Adobe Flash Media Server
[rtmpdump] DEBUG: HandShake: Handshaking finished....
[rtmpdump] DEBUG: RTMP_Connect1, handshaked
[rtmpdump] DEBUG: Invoking connect
[rtmpdump] INFO: Connected...
[rtmpdump] DEBUG: HandleServerBW: server BW = 2500000
[rtmpdump] DEBUG: HandleClientBW: client BW = 2500000 2
[rtmpdump] DEBUG: HandleChangeChunkSize, received: chunk size change to 16384
[rtmpdump] DEBUG: RTMP_ClientPacket, received: invoke 240 bytes
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: <Name:             fmsVer, STRING:	FMS/4,5,3,101>
[rtmpdump] DEBUG: Property: <Name:       capabilities, NUMBER:	255.00>
[rtmpdump] DEBUG: Property: <Name:               mode, NUMBER:	1.00>
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: <Name:              level, STRING:	status>
[rtmpdump] DEBUG: Property: <Name:               code, STRING:	NetConnection.Connect.Success>
[rtmpdump] DEBUG: Property: <Name:        description, STRING:	Connection succeeded.>
[rtmpdump] DEBUG: Property: <Name:     objectEncoding, NUMBER:	0.00>
[rtmpdump] DEBUG: Property: <Name:               data, OBJECT>
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: <Name:            version, STRING:	4,5,3,101>
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: HandleInvoke, server invoking <_result>
[rtmpdump] DEBUG: HandleInvoke, received result for method call <connect>
[rtmpdump] DEBUG: sending ctrl. type: 0x0003
[rtmpdump] DEBUG: Invoking createStream
[rtmpdump] DEBUG: FCSubscribe: stream_musify
[rtmpdump] DEBUG: Invoking FCSubscribe
[rtmpdump] DEBUG: RTMP_ClientPacket, received: invoke 21 bytes
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: NULL
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: HandleInvoke, server invoking <onBWDone>
[rtmpdump] DEBUG: Invoking _checkbw
[rtmpdump] DEBUG: RTMP_ClientPacket, received: invoke 29 bytes
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: NULL
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: HandleInvoke, server invoking <_result>
[rtmpdump] DEBUG: HandleInvoke, received result for method call <createStream>
[rtmpdump] DEBUG: SendPlay, seekTime=0, stopTime=0, sending play: stream_musify
[rtmpdump] DEBUG: Invoking play
[rtmpdump] DEBUG: sending ctrl. type: 0x0003
[rtmpdump] DEBUG: RTMP_ClientPacket, received: invoke 16419 bytes
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: NULL
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: HandleInvoke, server invoking <_onbwcheck>
[rtmpdump] DEBUG: Invoking _result
[rtmpdump] DEBUG: RTMP_ClientPacket, received: invoke 119 bytes
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: NULL
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: <Name:               code, STRING:	NetStream.Play.Start>
[rtmpdump] DEBUG: Property: <Name:            context, STRING:	4711169243041841519>
[rtmpdump] DEBUG: Property: <Name:        description, STRING:	stream_musify>
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: HandleInvoke, server invoking <onFCSubscribe>
[rtmpdump] DEBUG: RTMP_ClientPacket, received: invoke 21 bytes
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: NULL
[rtmpdump] DEBUG: Property: NULL
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: HandleInvoke, server invoking <_result>
[rtmpdump] DEBUG: HandleInvoke, received result for method call <FCSubscribe>
[rtmpdump] DEBUG: HandleChangeChunkSize, received: chunk size change to 16384
[rtmpdump] DEBUG: HandleCtrl, received ctrl. type: 0, len: 6
[rtmpdump] DEBUG: HandleCtrl, Stream Begin 1
[rtmpdump] DEBUG: RTMP_ClientPacket, received: invoke 168 bytes
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: NULL
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: <Name:              level, STRING:	status>
[rtmpdump] DEBUG: Property: <Name:               code, STRING:	NetStream.Play.Reset>
[rtmpdump] DEBUG: Property: <Name:        description, STRING:	Playing and resetting stream_musify.>
[rtmpdump] DEBUG: Property: <Name:            details, STRING:	stream_musify>
[rtmpdump] DEBUG: Property: <Name:           clientid, STRING:	oAA8woaA>
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: HandleInvoke, server invoking <onStatus>
[rtmpdump] DEBUG: HandleInvoke, onStatus: NetStream.Play.Reset
[rtmpdump] DEBUG: RTMP_ClientPacket, received: invoke 162 bytes
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: NULL
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: <Name:              level, STRING:	status>
[rtmpdump] DEBUG: Property: <Name:               code, STRING:	NetStream.Play.Start>
[rtmpdump] DEBUG: Property: <Name:        description, STRING:	Started playing stream_musify.>
[rtmpdump] DEBUG: Property: <Name:            details, STRING:	stream_musify>
[rtmpdump] DEBUG: Property: <Name:           clientid, STRING:	oAA8woaA>
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: HandleInvoke, server invoking <onStatus>
[rtmpdump] DEBUG: HandleInvoke, onStatus: NetStream.Play.Start
[rtmpdump] Starting Live Stream
[rtmpdump] DEBUG: RTMP_ClientPacket, received: notify 24 bytes
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: HandleCtrl, received ctrl. type: 31, len: 6
[rtmpdump] DEBUG: HandleCtrl, Stream BufferEmpty 1
[rtmpdump] DEBUG: RTMP_ClientPacket, received: invoke 57 bytes
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: NULL
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: HandleInvoke, server invoking <onBWDone>
[rtmpdump] DEBUG: RTMP_ClientPacket, received: invoke 40 bytes
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: NULL
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: HandleInvoke, server invoking <_onbwdone>
[rtmpdump] DEBUG: HandleCtrl, received ctrl. type: 32, len: 6
[rtmpdump] DEBUG: HandleCtrl, Stream BufferReady 1
[rtmpdump] DEBUG: ignoring too small audio packet: size: 0
[rtmpdump] DEBUG: HandleCtrl, received ctrl. type: 31, len: 6
[rtmpdump] DEBUG: HandleCtrl, Stream BufferEmpty 1
[rtmpdump] DEBUG: HandleCtrl, received ctrl. type: 32, len: 6
[rtmpdump] DEBUG: HandleCtrl, Stream BufferReady 1
[rtmpdump] DEBUG: ignoring too small audio packet: size: 0
[rtmpdump] DEBUG: HandleCtrl, received ctrl. type: 31, len: 6
[rtmpdump] DEBUG: HandleCtrl, Stream BufferEmpty 1
[rtmpdump] DEBUG: HandleCtrl, received ctrl. type: 32, len: 6
[rtmpdump] DEBUG: HandleCtrl, Stream BufferReady 1
[rtmpdump] DEBUG: RTMP_ClientPacket, received: invoke 150 bytes
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: NULL
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: <Name:              level, STRING:	status>
[rtmpdump] DEBUG: Property: <Name:               code, STRING:	NetStream.Play.UnpublishNotify>
[rtmpdump] DEBUG: Property: <Name:        description, STRING:	stream_musify is now unpublished.>
[rtmpdump] DEBUG: Property: <Name:           clientid, STRING:	oAA8woaA>
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: HandleInvoke, server invoking <onStatus>
[rtmpdump] DEBUG: HandleInvoke, onStatus: NetStream.Play.UnpublishNotify
[rtmpdump] DEBUG: Invoking deleteStream
[rtmpdump] DEBUG: Got Play.Complete or Play.Stop from server. Assuming stream is complete
[download] 0.00B at Unknown speed (00:26)
[rtmpdump] DEBUG: RTMP_Read returned: 0
[rtmpdump] Download complete
[rtmpdump] DEBUG: Closing connection.
[rtmpdump] 0 bytes
[download] 100% of 0.00B
```

Linux Void x64 musl MATE - Kernel version 4.3.3
youtube-dl version 2015-12-23 is okay

**Comment by dstftw** [comment]
This issue has been fixed and fix will be incorporated in the next version of youtube-dl. For now you can download selecting different format with `-f`.

**Comment by NimGangstaCat** [comment]
Hitbox streams (at least) still cannot be played since the fix.

The error is the following:
```
$ mpv http://www.hitbox.tv/musify
Playing: http://www.hitbox.tv/musify
[ffmpeg] RTMP_ReadPacket, failed to read RTMP packet header
Failed to open rtmp://edge.live.hitbox.tv/live/musify.
```

The work around `mpv $(youtube-dl -g "http://www.hitbox.tv/musify")` produces the exact same output.

Here's the full output:
```
$ youtube-dl -v http://www.hitbox.tv/musify
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.hitbox.tv/musify']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.04.24
[debug] Python version 2.7.11 - Linux-4.5.2_1-x86_64-with-glibc2.2.5
[debug] exe versions: ffmpeg 2.8.6, ffprobe 2.8.6, rtmpdump 2.4
[debug] Proxy map: {}
[hitbox:live] musify: Downloading JSON metadata
[hitbox:live] musify: Downloading metadata JSON
[debug] Invoking downloader on u'rtmp://edge.live.hitbox.tv/live/musify'
[download] Destination: Musify - 24_7 Music and Gaming Stream Friendly 2016-04-29 12_58-musify.mp4
[debug] rtmpdump command line: rtmpdump --verbose -r rtmp://edge.live.hitbox.tv/live/musify -o 'Musify - 24_7 Music and Gaming Stream Friendly 2016-04-29 12_58-musify.mp4.part' --swfVfy http://www.hitbox.tv/static/player/flowplayer/flowplayer.commercial-3.2.16.swf --pageUrl http://www.hitbox.tv/musify --live
[rtmpdump] RTMPDump v2.4
[rtmpdump] (c) 2010 Andrej Stepanchuk, Howard Chu, The Flvstreamer Team; license: GPL
[rtmpdump] DEBUG: Parsing...
[rtmpdump] DEBUG: Parsed protocol: 0
[rtmpdump] DEBUG: Parsed host    : edge.live.hitbox.tv
[rtmpdump] DEBUG: Parsed app     : live
[rtmpdump] DEBUG: Protocol : RTMP
[rtmpdump] DEBUG: Hostname : edge.live.hitbox.tv
[rtmpdump] DEBUG: Port     : 1935
[rtmpdump] DEBUG: Playpath : musify
[rtmpdump] DEBUG: tcUrl    : rtmp://edge.live.hitbox.tv:1935/live
[rtmpdump] DEBUG: swfUrl   : http://www.hitbox.tv/static/player/flowplayer/flowplayer.commercial-3.2.16.swf
[rtmpdump] DEBUG: pageUrl  : http://www.hitbox.tv/musify
[rtmpdump] DEBUG: app      : live
[rtmpdump] DEBUG: live     : yes
[rtmpdump] DEBUG: timeout  : 30 sec
[rtmpdump] DEBUG: SWFSHA256:
[rtmpdump] DEBUG: 75 20 ee cf 7b 4f 33 46 25 47 28 ab 53 ad 99 c4
[rtmpdump] DEBUG: bd 80 0e 34 c7 8c cf 47 55 31 70 a0 98 6b 88 a3
[rtmpdump] DEBUG: SWFSize  : 259809
[rtmpdump] DEBUG: Setting buffer time to: 36000000ms
[rtmpdump] Connecting ...
[rtmpdump] DEBUG: RTMP_Connect1, ... connected, handshaking
[rtmpdump] DEBUG: HandShake: Client type: 03
[rtmpdump] DEBUG: HandShake: Client digest offset: 430
[rtmpdump] DEBUG: HandShake: Initial client digest: 
[rtmpdump] DEBUG: eb 98 a0 33 c7 1c ac 9c d4 90 5d ad b9 1f e8 59
[rtmpdump] DEBUG: 65 2d 5d b7 71 5d b2 a1 6c bf 69 be f7 e8 99 f5
[rtmpdump] DEBUG: HandShake: Type Answer   : 03
[rtmpdump] DEBUG: HandShake: Server Uptime : 1638655804
[rtmpdump] DEBUG: HandShake: FMS Version   : 13.14.10.13
[rtmpdump] DEBUG: HandShake: Calculated digest key from secure key and server digest: 
[rtmpdump] DEBUG: 70 50 86 76 4d d6 2e 74 15 e6 1e 61 81 84 8d 0c
[rtmpdump] DEBUG: 25 03 ac dc 3d bb 19 12 8d c8 20 c5 48 ac 77 10
[rtmpdump] DEBUG: HandShake: Client signature calculated:
[rtmpdump] DEBUG: 68 01 c8 82 b1 9f 1e 1c c4 5e 06 39 6c 2d 87 91
[rtmpdump] DEBUG: a6 82 20 4b ec 7e c3 77 54 ca c7 93 8d fa 1f 18
[rtmpdump] DEBUG: HandShake: Server sent signature:
[rtmpdump] DEBUG: 85 13 52 eb 0f fc 4e 57 35 9b 92 e7 bb 7d c1 4d
[rtmpdump] DEBUG: 71 31 5c 58 ba 21 92 a4 ee 20 60 ce 92 70 85 de
[rtmpdump] DEBUG: HandShake: Digest key: 
[rtmpdump] DEBUG: 69 99 d1 79 7a 50 8b 40 bb 90 18 b0 9b 38 95 c7
[rtmpdump] DEBUG: 90 b9 73 0c d3 19 cc e2 e9 ea 18 e8 15 17 7a 98
[rtmpdump] DEBUG: HandShake: Signature calculated:
[rtmpdump] DEBUG: 85 13 52 eb 0f fc 4e 57 35 9b 92 e7 bb 7d c1 4d
[rtmpdump] DEBUG: 71 31 5c 58 ba 21 92 a4 ee 20 60 ce 92 70 85 de
[rtmpdump] DEBUG: HandShake: Genuine Adobe Flash Media Server
[rtmpdump] DEBUG: HandShake: Handshaking finished....
[rtmpdump] DEBUG: RTMP_Connect1, handshaked
[rtmpdump] DEBUG: Invoking connect
[rtmpdump] INFO: Connected...
[rtmpdump] DEBUG: HandleServerBW: server BW = 5000000
[rtmpdump] DEBUG: HandleClientBW: client BW = 5000000 2
[rtmpdump] DEBUG: HandleChangeChunkSize, received: chunk size change to 16384
[rtmpdump] DEBUG: RTMP_ClientPacket, received: invoke 190 bytes
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: <Name:             fmsVer, STRING:	FMS/3,0,1,123>
[rtmpdump] DEBUG: Property: <Name:       capabilities, NUMBER:	31.00>
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: <Name:              level, STRING:	status>
[rtmpdump] DEBUG: Property: <Name:               code, STRING:	NetConnection.Connect.Success>
[rtmpdump] DEBUG: Property: <Name:        description, STRING:	Connection succeeded.>
[rtmpdump] DEBUG: Property: <Name:     objectEncoding, NUMBER:	0.00>
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: HandleInvoke, server invoking <_result>
[rtmpdump] DEBUG: HandleInvoke, received result for method call <connect>
[rtmpdump] DEBUG: sending ctrl. type: 0x0003
[rtmpdump] DEBUG: Invoking createStream
[rtmpdump] DEBUG: FCSubscribe: musify
[rtmpdump] DEBUG: Invoking FCSubscribe
[rtmpdump] DEBUG: RTMP_ClientPacket, received: invoke 29 bytes
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: NULL
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: HandleInvoke, server invoking <_result>
[rtmpdump] DEBUG: HandleInvoke, received result for method call <createStream>
[rtmpdump] DEBUG: SendPlay, seekTime=0, stopTime=0, sending play: musify
[rtmpdump] DEBUG: Invoking play
[rtmpdump] DEBUG: sending ctrl. type: 0x0003
[rtmpdump] DEBUG: RTMP_ClientPacket, received: invoke 96 bytes
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: NULL
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: Property: <Name:              level, STRING:	status>
[rtmpdump] DEBUG: Property: <Name:               code, STRING:	NetStream.Play.Start>
[rtmpdump] DEBUG: Property: <Name:        description, STRING:	Start live>
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: HandleInvoke, server invoking <onStatus>
[rtmpdump] DEBUG: HandleInvoke, onStatus: NetStream.Play.Start
[rtmpdump] Starting Live Stream
[rtmpdump] DEBUG: RTMP_ClientPacket, received: notify 24 bytes
[rtmpdump] DEBUG: (object begin)
[rtmpdump] DEBUG: (object end)
[rtmpdump] DEBUG: RTMPSockBuf_Fill, recv returned -1. GetSockError(): 11 (Resource temporarily unavailable)
[rtmpdump] ERROR: RTMP_ReadPacket, failed to read RTMP packet header
[download] 0.00B at Unknown speed (00:32)
[rtmpdump] DEBUG: RTMP_Read returned: 0
[rtmpdump] Download may be incomplete (downloaded about 0.00%), try resuming
[rtmpdump] DEBUG: Closing connection.
[rtmpdump] DEBUG: Invoking deleteStream


ERROR: rtmpdump exited with code 2
  File "/usr/bin/youtube-dl", line 6, in <module>
    youtube_dl.main()
  File "/usr/lib/python2.7/site-packages/youtube_dl/__init__.py", line 419, in main
    _real_main(argv)
  File "/usr/lib/python2.7/site-packages/youtube_dl/__init__.py", line 409, in _real_main
    retcode = ydl.download(all_urls)
  File "/usr/lib/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 1732, in download
    url, force_generic_extractor=self.params.get('force_generic_extractor', False))
  File "/usr/lib/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 684, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/lib/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 729, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "/usr/lib/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 1378, in process_video_result
    self.process_info(new_info)
  File "/usr/lib/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 1640, in process_info
    success = dl(filename, info_dict)
  File "/usr/lib/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 1582, in dl
    return fd.download(name, info)
  File "/usr/lib/python2.7/site-packages/youtube_dl/downloader/common.py", line 350, in download
    return self.real_download(filename, info_dict)
  File "/usr/lib/python2.7/site-packages/youtube_dl/downloader/rtmp.py", line 202, in real_download
    self.report_error('rtmpdump exited with code %d' % retval)
  File "/usr/lib/python2.7/site-packages/youtube_dl/downloader/common.py", line 161, in report_error
    self.ydl.report_error(*args, **kargs)
  File "/usr/lib/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 547, in report_error
    self.trouble(error_message, tb)
  File "/usr/lib/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 509, in trouble
    tb_data = traceback.format_list(traceback.extract_stack())
```

Linux Void x64 Cinnamon - Kernel version 4.5.2
