### ISSUE TITLE
[youtube] No MPD manifest extracted for vevo videos

### ISSUE THREAD

**Issue by Klaus1189** [rg3/youtube-dl#8511]
```
Microsoft Windows [Version 10.0.10586]
(c) 2015 Microsoft Corporation. Alle Rechte vorbehalten.

C:\...\youtube-dl -F https://www.youtube.com/watch?v=jq30l5-vBbo
[youtube] jq30l5-vBbo: Downloading webpage
[youtube] jq30l5-vBbo: Downloading video info webpage
[youtube] jq30l5-vBbo: Extracting video information
[info] Available formats for jq30l5-vBbo:
format code  extension  resolution note
249          webm       audio only DASH audio   56k , opus @ 50k, 3.81MiB
250          webm       audio only DASH audio   82k , opus @ 70k, 5.15MiB
171          webm       audio only DASH audio  121k , vorbis@128k, 7.98MiB
140          mp4        audio only DASH audio  128k , m4a_dash container, mp4a.40.2@128k, 9.88MiB
251          webm       audio only DASH audio  156k , opus @160k, 9.95MiB
160          mp4        256x144    144p  114k , avc1.4d400c, 24fps, video only, 8.62MiB
133          mp4        426x240    240p  249k , avc1.4d4015, 24fps, video only, 19.04MiB
134          mp4        640x360    360p  648k , avc1.4d401e, 24fps, video only, 35.26MiB
135          mp4        854x480    480p 1178k , avc1.4d401e, 24fps, video only, 75.61MiB
136          mp4        1280x720   720p 2354k , avc1.4d401f, 24fps, video only, 157.40MiB
137          mp4        1920x1080  1080p 4566k , avc1.640028, 24fps, video only, 320.37MiB
36           3gp        ?x320      small , mp4v.20.3,  mp4a.40.2
17           3gp        176x144    small , mp4v.20.3,  mp4a.40.2@ 24k
5            flv        400x240    small , h263, mp3  @ 64k
43           webm       640x360    medium , vp8.0,  vorbis@128k
18           mp4        640x360    medium , avc1.42001E,  mp4a.40.2@ 96k
22           mp4        1280x720   hd720 , avc1.64001F,  mp4a.40.2@192k (best)
```

samples:
WQv88iB02oU
7MKjNVw35Ss
WAbvP9GEIsE
oDPda4iyoQk

**Comment by dstftw** [comment]
These are the consequences of not extracted DASH manifest. Only vevo videos are affected.

**Comment by Klaus1189** [comment]
OK, why is the dash manifest not extracted? To be honest I don't even know what this means. 
I just recognized youtube-dl is "extracting MPD manifest". Is this correct? And again I don't know what youtube-dl is doing there.

**Comment by Klaus1189** [comment]
Is there a way to download the dash webm videos of vevo youtube videos?

**Comment by dstftw** [comment]
As usual with 9c7b38981cb6429ba690aaef313e36fb694f9902.

**Comment by Klaus1189** [comment]
Sorry, but what do I have to do?

**Comment by dstftw** [comment]
Run youtube-dl from sources or wait for a new release.

**Comment by Klaus1189** [comment]
Ahh OK, I got it. Thanks

**Comment by 0xABC** [comment]
@dstftw are you suggesting this issue is fixed in the latest source? That doesn't seem to be the case.

**Comment by dstftw** [comment]
It's not fixed it's worked around. These formats served not only within MPD manifest.

**Comment by Klaus1189** [comment]
What is the difference between fixed and worked around?
The dash webm are in the source available as you already mentioned, right?

**Comment by 0xABC** [comment]
@dstftw (and anyone else) any suggestions for someone trying to solve this issue? (I want the actual MPD manifest, not a workaround to get the formats it contains.) I’m willing to take a stab at this if I can get some direction. Thank you.

**Comment by dstftw** [comment]
I personally don't see much point investing time in this since it won't bring any crucial benefit.

**Comment by 0xABC** [comment]
@dstftw I know it may not bring a significant benefit to the typical youtube-dl user, but from my perspective it is crucial and it would be worth investing the time if I knew what to do.

**Comment by Hrxn** [comment]
@0xABC Could you give an example, maybe? What is different with the MPD manifest?
I'd just like to understand a possible use case..

**Comment by 0xABC** [comment]
@Hrxn I am actually using the MPD manifest in a video player to play the video with the DASH feature.

**Comment by yan12125** [comment]
All videos mentioned here have the same problem as examples in #5118. Briefly, there's currenly no known way to download DASH MPD manifests found in ```get_video_info``` pages declared with ```use_cipher_signature=True```. If you know how, please propose it.
