### ISSUE TITLE
[GDCVault] Some video still can't download

### ISSUE THREAD

**Issue by Farl** [rg3/youtube-dl#9155]
Sorry.. It's me again.
I have found more video that can't download from GDCVault

Here's the list
http://www.gdcvault.com/play/1023189/download
http://www.gdcvault.com/play/1023196/download
http://www.gdcvault.com/play/1023197/download
http://www.gdcvault.com/play/1023247/download
http://www.gdcvault.com/play/1023262/download
http://www.gdcvault.com/play/1023264/download
http://www.gdcvault.com/play/1023284/download
http://www.gdcvault.com/play/1023291/download
http://www.gdcvault.com/play/1023314/download
http://www.gdcvault.com/play/1023334/download
http://www.gdcvault.com/play/1023334/download
http://www.gdcvault.com/play/1023392/download
http://www.gdcvault.com/play/1023397/download
http://www.gdcvault.com/play/1023416/download
http://www.gdcvault.com/play/1023432/download
http://www.gdcvault.com/play/1023460/download
http://www.gdcvault.com/play/1023472/download
http://www.gdcvault.com/play/1023493/download
http://www.gdcvault.com/play/1023542/download
http://www.gdcvault.com/play/1023548/download
http://www.gdcvault.com/play/1023550/download
http://www.gdcvault.com/play/1023551/download
http://www.gdcvault.com/play/1023558/download
http://www.gdcvault.com/play/1023561/download
http://www.gdcvault.com/play/1023561/download
http://www.gdcvault.com/play/1023574/download
http://www.gdcvault.com/play/1023585/download
http://www.gdcvault.com/play/1023612/download
http://www.gdcvault.com/play/1023642/download
http://www.gdcvault.com/play/1023643/download
http://www.gdcvault.com/play/1023644/download
http://www.gdcvault.com/play/1023645/download
http://www.gdcvault.com/play/1023646/download
http://www.gdcvault.com/play/1023647/download
http://www.gdcvault.com/play/1023648/download
http://www.gdcvault.com/play/1023649/download
http://www.gdcvault.com/play/1023650/download
http://www.gdcvault.com/play/1023651/download
http://www.gdcvault.com/play/1023652/download
http://www.gdcvault.com/play/1023653/download
http://www.gdcvault.com/play/1023654/download
http://www.gdcvault.com/play/1023655/download
http://www.gdcvault.com/play/1023656/download
http://www.gdcvault.com/play/1023657/download
http://www.gdcvault.com/play/1023658/download
http://www.gdcvault.com/play/1023659/download
http://www.gdcvault.com/play/1023660/download
http://www.gdcvault.com/play/1023661/download
http://www.gdcvault.com/play/1023662/download
http://www.gdcvault.com/play/1023663/download
http://www.gdcvault.com/play/1023664/download
http://www.gdcvault.com/play/1023665/download
http://www.gdcvault.com/play/1023666/download
http://www.gdcvault.com/play/1023667/download
http://www.gdcvault.com/play/1023668/download
http://www.gdcvault.com/play/1023669/download
http://www.gdcvault.com/play/1023670/download
http://www.gdcvault.com/play/1023671/download
http://www.gdcvault.com/play/1023672/download
http://www.gdcvault.com/play/1023673/download
http://www.gdcvault.com/play/1023674/download

Here's the log

[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'http://www.gdcvault.com/play/1023189/download', u'
--output', u'\\\\192.168.1.137\\GDCVault\\GDC 2016\\%(title)s -%(id)s.%(ext)s',
u'--username', u'PRIVATE', u'--password', u'PRIVATE', u'-v']
[debug] Encodings: locale cp950, fs mbcs, out cp950, pref cp950
[debug] youtube-dl version 2016.04.06
[debug] Python version 2.7.10 - Windows-7-6.1.7601-SP1
[debug] exe versions: none
[debug] Proxy map: {}
[GDCVault] download: Downloading webpage
[GDCVault] download: Logging in
[GDCVault] download: Getting authenticated video page
[GDCVault] download: Logging out
[GDCVault] download: Downloading XML
Traceback (most recent call last):
  File "__main__.py", line 19, in <module>
  File "youtube_dl\__init__.pyo", line 419, in main
  File "youtube_dl\__init__.pyo", line 409, in _real_main
  File "youtube_dl\YoutubeDL.pyo", line 1725, in download
  File "youtube_dl\YoutubeDL.pyo", line 669, in extract_info
  File "youtube_dl\extractor\common.pyo", line 323, in extract
  File "youtube_dl\extractor\gdcvault.pyo", line 190, in _real_extract
  File "youtube_dl\extractor\gdcvault.pyo", line 92, in _parse_flv
  File "youtube_dl\utils.pyo", line 1478, in remove_end
AttributeError: 'NoneType' object has no attribute 'endswith'

**Comment by dstftw** [comment]
This issue is already fixed and fix will be incorporated in the next version of youtube-dl.

**Comment by Farl** [comment]
Thanks

**Comment by Farl** [comment]
Hi dstftw,

I have already clone the latest code and run by python.
But still have some video can't be downloaded.

http://www.gdcvault.com/play/1023189/download
http://www.gdcvault.com/play/1023196/download
http://www.gdcvault.com/play/1023197/download
http://www.gdcvault.com/play/1023247/download
http://www.gdcvault.com/play/1023262/download
http://www.gdcvault.com/play/1023264/download
http://www.gdcvault.com/play/1023284/download
http://www.gdcvault.com/play/1023291/download
http://www.gdcvault.com/play/1023314/download
http://www.gdcvault.com/play/1023334/download
http://www.gdcvault.com/play/1023334/download
http://www.gdcvault.com/play/1023392/download
http://www.gdcvault.com/play/1023397/download
http://www.gdcvault.com/play/1023416/download
http://www.gdcvault.com/play/1023432/download
http://www.gdcvault.com/play/1023460/download
http://www.gdcvault.com/play/1023472/download
http://www.gdcvault.com/play/1023493/download
http://www.gdcvault.com/play/1023542/download
http://www.gdcvault.com/play/1023548/download
http://www.gdcvault.com/play/1023550/download
http://www.gdcvault.com/play/1023551/download
http://www.gdcvault.com/play/1023558/download
http://www.gdcvault.com/play/1023561/download
http://www.gdcvault.com/play/1023561/download
http://www.gdcvault.com/play/1023574/download
http://www.gdcvault.com/play/1023585/download
http://www.gdcvault.com/play/1023646/download

**Comment by Farl** [comment]
Log

[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['http://www.gdcvault.com/play/1023646/download', '--
output', '\\\\192.168.88.194\\upload\\GDC 2016\\add\\%(title)s -%(id)s.%(ext)s',
 '--username', 'PRIVATE', '--password', 'PRIVATE', '-v']
[debug] Encodings: locale cp950, fs mbcs, out cp950, pref cp950
[debug] youtube-dl version 2016.04.06
[debug] Python version 3.5.1 - Windows-7-6.1.7601-SP1
[debug] exe versions: none
[debug] Proxy map: {}
[GDCVault] download: Downloading webpage
[GDCVault] download: Downloading XML
Traceback (most recent call last):
  File "C:\Users\Farl\AppData\Local\Programs\Python\Python35-32\lib\runpy.py", l
ine 170, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\Farl\AppData\Local\Programs\Python\Python35-32\lib\runpy.py", l
ine 85, in _run_code
    exec(code, run_globals)
  File "F:\Documents\GitHub\youtube-dl\youtube_dl\__main__.py", line 19, in <mod
ule>
    youtube_dl.main()
  File "F:\Documents\GitHub\youtube-dl\youtube_dl\__init__.py", line 419, in mai
n
    _real_main(argv)
  File "F:\Documents\GitHub\youtube-dl\youtube_dl\__init__.py", line 409, in _re
al_main
    retcode = ydl.download(all_urls)
  File "F:\Documents\GitHub\youtube-dl\youtube_dl\YoutubeDL.py", line 1730, in d
ownload
    url, force_generic_extractor=self.params.get('force_generic_extractor', Fals
e))
  File "F:\Documents\GitHub\youtube-dl\youtube_dl\YoutubeDL.py", line 671, in ex
tract_info
    ie_result = ie.extract(url)
  File "F:\Documents\GitHub\youtube-dl\youtube_dl\extractor\common.py", line 341
, in extract
    return self._real_extract(url)
  File "F:\Documents\GitHub\youtube-dl\youtube_dl\extractor\gdcvault.py", line 1
92, in _real_extract
    video_formats = self._parse_flv(xml_description)
  File "F:\Documents\GitHub\youtube-dl\youtube_dl\extractor\gdcvault.py", line 9
2, in _parse_flv
    'play_path': remove_end(slide_video_path, '.flv'),
  File "F:\Documents\GitHub\youtube-dl\youtube_dl\utils.py", line 1478, in remov
e_end
    if s.endswith(end):
AttributeError: 'NoneType' object has no attribute 'endswith'

**Comment by yan12125** [comment]
Version 2016.04.13 is just released. Could you try again?

**Comment by Farl** [comment]
Thank for your remind.
I have try the 4.13 version.
Still show the same error message.

[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'http://www.gdcvault.com/play/1023189/Co-Development-Open-and-Agile', u'-u', u'PRIVATE', u'-p', u'PRIVATE', u'-v']
[debug] Encodings: locale cp950, fs mbcs, out cp950, pref cp950
[debug] youtube-dl version 2016.04.13
[debug] Python version 2.7.10 - Windows-8-6.2.9200
[debug] exe versions: none
[debug] Proxy map: {}
[GDCVault] Co-Development-Open-and-Agile: Downloading webpage
[GDCVault] Co-Development-Open-and-Agile: Logging in
[GDCVault] Co-Development-Open-and-Agile: Getting authenticated video page
[GDCVault] Co-Development-Open-and-Agile: Logging out
[GDCVault] Co-Development-Open-and-Agile: Downloading XML
Traceback (most recent call last):
  File "__main__.py", line 19, in <module>
  File "youtube_dl\__init__.pyo", line 419, in main
  File "youtube_dl\__init__.pyo", line 409, in _real_main
  File "youtube_dl\YoutubeDL.pyo", line 1730, in download
  File "youtube_dl\YoutubeDL.pyo", line 671, in extract_info
  File "youtube_dl\extractor\common.pyo", line 341, in extract
  File "youtube_dl\extractor\gdcvault.pyo", line 192, in _real_extract
  File "youtube_dl\extractor\gdcvault.pyo", line 92, in _parse_flv
  File "youtube_dl\utils.pyo", line 1478, in remove_end
AttributeError: 'NoneType' object has no attribute 'endswith'

**Comment by dstftw** [comment]
This video is only available for subscribed users thus you have to provide account credentials.

**Comment by Farl** [comment]
Hi dstftw,
I can watch this video ('http://www.gdcvault.com/play/1023189/Co-Development-Open-and-Agile') on my browser (with my account).
So I think that problem is not cause by account credentials.

**Comment by dstftw** [comment]
Try **without** account obviously.

**Comment by Farl** [comment]
Sorry. I can't understand.
I know I have to login for watching these videos.
So I input the same username and password when I use youtube-dl.
What am I missing?

**Comment by dstftw** [comment]
I **do not** have an account. This video can not be played without an account. Thus I am unable to figure out what's wrong.

**Comment by Farl** [comment]
OK. Now I get it.
Is there anyone can help me?
Or maybe you can teach me how to debug this issue?

**Comment by Farl** [comment]
I try to trace the code and find that there is no <mp4video> in the xml.
Here is the xml content

<?xml version="1.0"?>
<podiumPresentation><metadata><id>836748_MFZS</id><title><![CDATA[Co-Development: Open and Agile Game Development]]></title><speaker><![CDATA[Starr Long]]></speaker><startTime>00:00:00</startTime><endTime>00:30:25</endTime><aspectRatio/><language/><thumbnail/><modified>2016-04-06 12:02:45</modified><date/><duration/><linkCode/><embedCode/><virtualEDL/><akamaiHost>fms-u.digitallyspeaking.com/cfx/st</akamaiHost>
<speakerVideo/>
<slideVideo/>
<MBRVideos>
<MBRVideo>
  <streamName>mp4:assets/ubm/gdc/sf16/836748_MFZS-v74ec2-500.mp4</streamName><bitrate>564</bitrate>
</MBRVideo>
<MBRVideo>
  <streamName>mp4:assets/ubm/gdc/sf16/836748_MFZS-v74ec2-800.mp4</streamName><bitrate>864</bitrate>
</MBRVideo>
<MBRVideo>
  <streamName>mp4:assets/ubm/gdc/sf16/836748_MFZS-v74ec2-1300.mp4</streamName><bitrate>1364</bitrate>
</MBRVideo>
</MBRVideos></metadata><chapters><chapter><time>00:00:05</time><title><![CDATA[Welcome]]></title></chapter><chapter><time>00:01:01</time><title><![CDATA[About Me]]></title></chapter><chapter><time>00:01:34</time><title><![CDATA[Co-Development : Core Concepts]]></title></chapter><chapter><time>00:01:59</time><title><![CDATA[Transparency]]></title></chapter><chapter><time>00:07:22</time><title><![CDATA[Transparency (Continued)]]></title></chapter><chapter><time>00:11:27</time><title><![CDATA[Cadence]]></title></chapter><chapter><time>00:14:22</time><title><![CDATA[Feedback Loop]]></title></chapter><chapter><time>00:19:35</time><title><![CDATA[Feedback Loop (Continued)]]></title></chapter><chapter><time>00:24:48</time><title><![CDATA[Challenges]]></title></chapter><chapter><time>00:28:39</time><title><![CDATA[Q&A]]></title></chapter><chapter><time>00:30:13</time><title><![CDATA[Thank you]]></title></chapter></chapters></podiumPresentation>
