### ISSUE TITLE
[iQIYI]Unable to download the correct video,It parses the ads.

### ISSUE THREAD

**Issue by M0ment** [rg3/youtube-dl#9839]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.06.19.1*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.06.19.1**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add `-v` flag to **your command line** you run youtube-dl with, copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):
```
$ youtube-dl -v <your command line>
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'-v', u'http://www.youtube.com/watch?v=BaW_jenozKcj']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2016.06.19.1
[debug] Python version 2.7.11 - Windows-2003Server-5.2.3790-SP2
[debug] exe versions: ffmpeg N-75573-g1d0487f, ffprobe N-75573-g1d0487f, rtmpdump 2.4
[debug] Proxy map: {}
...
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://www.youtube.com/watch?v=BaW_jenozKc
- Single video: https://youtu.be/BaW_jenozKc
- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

---

### Description of your *issue*, suggested solution and other information

Explanation of your *issue* in arbitrary form goes here. Please make sure the [description is worded well enough to be understood](https://github.com/rg3/youtube-dl#is-the-description-of-the-issue-itself-sufficient). Provide as much context and examples as possible.
If work on your *issue* required an account credentials please provide them or explain how one can obtain them.

youtube-dl -v -F http://www.iqiyi.com/v_19rrkyywoo.html
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v', '-F', 'http://www.iqiyi.com/v_19rrkyywoo.html']
[debug] Encodings: locale cp936, fs mbcs, out cp936, pref cp936
[debug] youtube-dl version 2016.06.19.1
[debug] Python version 3.5.1 - Windows-10-10.0.10586-SP0
[debug] exe versions: ffmpeg 3.0
[debug] Proxy map: {}
[iqiyi] temp_id: download video page
[iqiyi] 7f13d67408c4d737588e84d3c8b0985b: Downloading JSON metadata
[iqiyi] 7f13d67408c4d737588e84d3c8b0985b: Download path key of segment 1 for format h3
[iqiyi] 7f13d67408c4d737588e84d3c8b0985b: Download video info of segment 1 for format h3
[iqiyi] 7f13d67408c4d737588e84d3c8b0985b: Download path key of segment 1 for format h6
[iqiyi] 7f13d67408c4d737588e84d3c8b0985b: Download video info of segment 1 for format h6
[iqiyi] 7f13d67408c4d737588e84d3c8b0985b: Download path key of segment 1 for format h5
[iqiyi] 7f13d67408c4d737588e84d3c8b0985b: Download video info of segment 1 for format h5
[info] Available formats for 7f13d67408c4d737588e84d3c8b0985b:
format code  extension  resolution note
h6           f4v        unknown    4.29MiB
h5           f4v        unknown    6.63MiB
h3           f4v        unknown    16.39MiB (best)

This URL is a 40-minute video,Thisa result is wrong.Please fix this,thanks.

**Comment by yan12125** [comment]
Partially fixed in 5b6ad86. Now youtube-dl can download the low-resolution version.

**Comment by M0ment** [comment]
谢谢了~不过我主要还是需要VIP，1080p和4K的解析，能破解低清很不错了，大神们继续加油。Thanks.

**Comment by yan12125** [comment]
VIP-only videos are on the plan. I'll try to download all resolutions for ordinary videos first.

By the way, please use English as much as possible so that others can understand the situation.

**Comment by yan12125** [comment]
@M0ment Iqiyi is fixed in 2644e911bebcace4fbac7ddd3ea8c71936b1b3e9. I guess VIP videos work as usual. Could you try it?

**Comment by M0ment** [comment]
@yan12125 I find that it can support more formats,but no 4K.And VIP videos are still not woking.
`youtube-dl -v -F --cookies cookies.txt http://www.iqiyi.com/v_19rrldv28w.html
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v', '-F', '--cookies', 'cookies.txt', 'http://www.iqiyi.com/v_19rrldv28w.html']
[debug] Encodings: locale cp936, fs mbcs, out cp936, pref cp936
[debug] youtube-dl version 2016.07.03.1
[debug] Python version 3.4.4 - Windows-10-10.0.10586
[debug] exe versions: none
[debug] Proxy map: {}
[iqiyi] temp_id: download video page
[iqiyi] e0f9e3b03039e1ab7113f1d27672f33b: Downloading JSON metadata
ERROR: Unable to load data. Error code: A00011; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpapfvv6m8\build\youtube_dl\YoutubeDL.py", line 676, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpapfvv6m8\build\youtube_dl\extractor\common.py", line 343, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpapfvv6m8\build\youtube_dl\extractor\iqiyi.py", line 360, in _real_extract
youtube_dl.utils.ExtractorError: Unable to load data. Error code: A00011; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.`

**Comment by yan12125** [comment]
Could you try ```-u <username> -p <password>```? If I remember it correctly ```--cookies``` does not work with Iqiyi.

**Comment by M0ment** [comment]
Still not working.
```
youtube-dl -v -u ih34961908shis@163.com -p gh27591258 -F http://www.iqiyi.com/v_19rrldv28w.html
[debug] System config: []
[debug] User config: []
[debug] Command-line args: ['-v', '-u', 'PRIVATE', '-p', 'PRIVATE', '-F', 'http://www.iqiyi.com/v_19rrldv28w.html']
[debug] Encodings: locale cp936, fs mbcs, out cp936, pref cp936
[debug] youtube-dl version 2016.07.03.1
[debug] Python version 3.4.4 - Windows-10-10.0.10586
[debug] exe versions: none
[debug] Proxy map: {}
[iqiyi] Get token for logging
[iqiyi] Validate credentials
WARNING: unable to log in: please login via the web interface and enter the CAPTCHA code
[iqiyi] temp_id: download video page
[iqiyi] e0f9e3b03039e1ab7113f1d27672f33b: Downloading JSON metadata
ERROR: Unable to load data. Error code: A00011; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpapfvv6m8\build\youtube_dl\YoutubeDL.py", line 676, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpapfvv6m8\build\youtube_dl\extractor\common.py", line 343, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpapfvv6m8\build\youtube_dl\extractor\iqiyi.py", line 360, in _real_extract
youtube_dl.utils.ExtractorError: Unable to load data. Error code: A00011; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by yan12125** [comment]
> WARNING: unable to log in: please login via the web interface and enter the CAPTCHA code

Maybe something has changed at Iqiyi. Have you tried to login via the web interface and enter the CAPTCHA code?

**Comment by M0ment** [comment]
I have logged in iqiyi's website, and I can watch this video online. But the result is same.

**Comment by yan12125** [comment]
Need a pair of valid username/password for further testing. If you **trust** me, you can drop me a mail with the username and the password.

**IMPORTANT**: If I remember it correctly Iqiyi doesn't like logging from multiple geographic locations. I'm in Taiwan and I'm not sure whether your account may be locked or not if I log in here.

**Comment by M0ment** [comment]
@yan12125 I have sent my account to your email. Please check.

**Comment by yan12125** [comment]
@M0ment Could you try this branch? https://github.com/yan12125/youtube-dl/tree/iqiyi-vcode

It will ask you the verification code. The code can be found in a image file captcha.gif

**Comment by yan12125** [comment]
@M0ment Do you have a VIP-only video that is available outside Mainland China? I can't find a working proxy for VIP-only videos.

**Comment by M0ment** [comment]
@yan12125 I'm sorry, I can't find.

**Comment by yan12125** [comment]
Never mind. Let's wait until someone finds a way for people outside Mainland China to watch VIP-only videos.

**Comment by ztytian** [comment]
Hello. You can get a proxy here. Use OpenVPN to connect. https://vnet.one/?rc=2879

**Comment by xiayyu** [comment]
@yan12125 I have tested in mainland, login properly, but the url return is still non-vip addr and 6 min video is downloaded. In fact, when I switch web browser (chrome to firefox) with the same PC, later login would disable the former one. I am just wondering why mobile port is used for iqiyi for current version, what happed to the PC port?

**Comment by yan12125** [comment]
> what happed to the PC port

I can't reverse iqiyi's code from complicated SWF files. If you know how feel free to open an pull request.

**Comment by xiayyu** [comment]
@yan12125 
take a look of this https://github.com/zhangn1985/ykdl/issues/19
there is no need to crack SWF, the key value of `vf` can be calculate by the function `cmd5x` and for vip-only video another key value `ibt` is also gen by `cmd5x`, which is easy to found in the js. 
function `cmd5x` is not trivial but someone already cracked it.

**Comment by yan12125** [comment]
Looks good. But we can't use it directly without explicit permissions due to licensing restrictions. zhangn1985/ykdl is licensed under MIT and the original code https://github.com/tuling56/Python/blob/master/Projects/down_video/iqiyi_video_download.py has no license declarations.
